/* BIOL 235 Unit 1 - Chapter 1: An Introduction to the Human Body
   试点章节数据：术语50 + 考点提炼 + 测验25题 + 费曼任务3
   内容依据: Tortora 15th Ch.1 定制课本 + Study Guide Objectives */
var NURS_CH1 = {
id:"ch1", unit:1, zh:"第一章：人体概述",
terms:[
{w:"anatomy",zh:"解剖学（研究身体结构及其相互关系）"},
{w:"physiology",zh:"生理学（研究身体功能，即各部分如何工作）"},
{w:"dissection",zh:"解剖（小心切开身体结构以研究其关系）"},
{w:"metabolism",zh:"新陈代谢（体内发生的全部化学过程的总和）"},
{w:"catabolism",zh:"分解代谢（复杂物质分解为简单成分）"},
{w:"anabolism",zh:"合成代谢（由小分子合成复杂物质）"},
{w:"responsiveness",zh:"应激性（觉察并响应环境变化的能力）"},
{w:"differentiation",zh:"分化（细胞由非特化发育为特化状态）"},
{w:"stem cell",zh:"干细胞（可分裂并分化为特化细胞的前体细胞）"},
{w:"homeostasis",zh:"稳态（内环境相对稳定的状态）"},
{w:"receptor",zh:"感受器（监测受控条件变化，向控制中枢发送信息）"},
{w:"control center",zh:"控制中枢（如脑，设定调定点并发出指令）"},
{w:"effector",zh:"效应器（接收指令并产生反应，改变受控条件）"},
{w:"afferent pathway",zh:"传入通路（信息流向控制中枢）"},
{w:"efferent pathway",zh:"传出通路（信息离开控制中枢）"},
{w:"negative feedback",zh:"负反馈（逆转受控条件的变化）"},
{w:"positive feedback",zh:"正反馈（加强受控条件的变化）"},
{w:"baroreceptor",zh:"压力感受器（血管壁中感知血压变化的神经细胞）"},
{w:"oxytocin",zh:"催产素（分娩时垂体释放，促进子宫收缩）"},
{w:"intracellular fluid",zh:"细胞内液 ICF（细胞内部的液体）"},
{w:"extracellular fluid",zh:"细胞外液 ECF（细胞外部的液体，即内环境）"},
{w:"interstitial fluid",zh:"组织液（组织细胞之间狭窄间隙中的ECF）"},
{w:"plasma",zh:"血浆（血管内的ECF）"},
{w:"anatomical position",zh:"解剖学标准姿势（直立、面向前、双足平行、手掌向前）"},
{w:"prone",zh:"俯卧位（脸朝下躺）"},
{w:"supine",zh:"仰卧位（脸朝上躺）"},
{w:"superior",zh:"上方的（朝向头部）"},
{w:"inferior",zh:"下方的（远离头部）"},
{w:"anterior",zh:"前方的（腹侧 ventral）"},
{w:"posterior",zh:"后方的（背侧 dorsal）"},
{w:"medial",zh:"内侧的（近身体中线）"},
{w:"lateral",zh:"外侧的（远身体中线）"},
{w:"proximal",zh:"近端的（近肢体与躯干连接处）"},
{w:"distal",zh:"远端的（远肢体与躯干连接处）"},
{w:"superficial",zh:"浅表的（近体表）"},
{w:"deep",zh:"深部的（远体表）"},
{w:"sagittal plane",zh:"矢状面（将身体分为左右两部分的纵切面）"},
{w:"midsagittal plane",zh:"正中矢状面（经过中线，均分左右）"},
{w:"frontal plane",zh:"额状面/冠状面（分为前后两部分）"},
{w:"transverse plane",zh:"横切面（分为上下两部分，又称水平面）"},
{w:"cranial cavity",zh:"颅腔（颅骨围成，容纳脑）"},
{w:"vertebral canal",zh:"椎管（脊柱围成，容纳脊髓）"},
{w:"thoracic cavity",zh:"胸腔（肋骨、胸肌、胸骨、胸椎围成）"},
{w:"pleural cavity",zh:"胸膜腔（包绕肺的潜在腔隙）"},
{w:"pericardial cavity",zh:"心包腔（包绕心脏的潜在腔隙）"},
{w:"mediastinum",zh:"纵隔（两肺之间，除肺外所有胸腔器官所在）"},
{w:"abdominopelvic cavity",zh:"腹盆腔（膈至腹股沟，含腹腔和盆腔）"},
{w:"peritoneum",zh:"腹膜（腹腔的浆膜）"},
{w:"parietal layer",zh:"壁层（衬于体腔壁的浆膜层）"},
{w:"visceral layer",zh:"脏层（覆盖脏器表面的浆膜层）"},
{w:"meninges",zh:"脑膜（保护脑和脊髓的三层膜）"},
{w:"viscera",zh:"内脏（胸腔和腹盆腔内的器官）"},
{w:"diaphragm",zh:"膈（分隔胸腔与腹腔的肌肉）"},
{w:"serous fluid",zh:"浆液（浆膜层间的润滑液）"},
{w:"disorder",zh:"功能紊乱（身体功能异常但无结构改变）"},
{w:"disease",zh:"疾病（有明确结构/功能改变的病理状态）"},
{w:"symptom",zh:"症状（病人主观感受到的异常）"},
{w:"sign",zh:"体征（可被观察/测量到的异常）"},
{w:"stimulus",zh:"刺激（引起反馈系统反应的变化）"},
{w:"set point",zh:"调定点（控制中枢设定的受控条件标准值）"},
{w:"autopsy",zh:"尸检（死后检查以确定死因）"},
{w:"epigastric",zh:"上腹区（九分区中央上部，肝大部在此）"},
{w:"hypogastric",zh:"下腹区/耻区（九分区中央下部，膀胱在此）"},
{w:"umbilical region",zh:"脐区（九分区正中央）"},
{w:"right lumbar",zh:"右腰区（九分区右侧中部，升结肠在此）"}
],
points:[
{t:"1.1 解剖与生理", items:[
"Anatomy 研究身体 structures 及其相互关系（dissection=切开研究）；Physiology 研究 body functions（各部分如何工作）",
"结构决定功能：颅骨skull紧密结合保护脑，指骨phalanges连接松散以便活动，肺泡壁alveolar wall极薄利于气体交换",
"解剖学分支：gross（regional/systemic/surface）· microscopic（histology组织学/cytology细胞学）· developmental/embryology胚胎学 · pathological病理解剖 · radiographic/imaging anatomy影像解剖。生理学分支：neuro · endocrine · cardiovascular · immunology · respiratory · renal · exercise · pathophysiology",
"Wiley常考两学科：pharmacology=药物作用与治疗；epidemiology=疾病在人群中的发生、传播原因"]},
{t:"1.2 六个结构层次", items:[
"chemical（atom原子=最小物质单位，molecule分子=2+原子结合；必需元素C/H/O/N/P/Ca/S；如DNA、葡萄糖）→ cellular（cell细胞=最小生命单位）→ tissue（四种基本组织）→ organ（两种以上组织，如胃）→ system（11大系统）→ organismal（organism个体）",
"四种组织功能：epithelial覆盖/衬里/成腺；connective连接支持保护+分布血管；muscular收缩产热促运动；nervous经神经冲动传递信息。胃stomach例：外层上皮+结缔减摩擦→3层平滑肌搅拌→内层上皮分泌消化液",
"11大系统：integumentary, skeletal, muscular, nervous, endocrine, cardiovascular, lymphatic, respiratory, digestive, urinary, reproductive。注意：胰腺pancreas横跨消化digestive+内分泌endocrine两个系统；皮肤skin是organ（由上皮+结缔+肌肉+神经多种组织构成），不是tissue",
"细胞学说cell theory：一切生物由细胞组成；原核生物prokaryotes为单细胞生物",
"书本类比（Wiley高频）：把身体比作一本书——cells=单词words，tissues=段落paragraphs，organs=章节chapters，systems=整本书book"]},
{t:"1.3 六大生命活动", items:[
"metabolism=catabolism（分解breakdown，如蛋白质protein→氨基酸amino acids）+anabolism（合成）；responsiveness（应激：神经细胞→action potentials，肌细胞→收缩）；movement（全身/器官如胆囊排胆汁/细胞如白细胞迁移/细胞内如分泌囊泡）；growth（细胞增大/增多，骨矿物质沉积）；differentiation（干细胞stem cells→特化，如红骨髓前体→红/白细胞）；reproduction（新细胞修复 或 受精fertilization→zygote产生新个体）",
"四种非侵入诊断：inspection视诊（观察）· palpation触诊（手摸）· auscultation听诊（听诊器听）· percussion叩诊（指叩听音，空腔与实心器官声音不同）",
"autopsy=死后尸检：确认死因、发现生前未检出疾病、协助教学与统计。死亡三指征：心跳停止loss of heartbeat、无自主呼吸no spontaneous breathing、脑功能丧失loss of brain function",
"科学方法（Wiley补充·非教材第1章原文）：hypothesis-based science=从具体假说出发再检验；用deductive reasoning演绎推理；证据不支持→修改假说再实验"]},
{t:"1.4 稳态与反馈", items:[
"homeostasis=内环境internal environment（ECF）相对稳定，是动态平衡。ECF包括：组织液 interstitial fluid、血浆 plasma、淋巴 lymph、脑脊液 cerebrospinal fluid、滑液 synovial fluid、房水玻璃体 aqueous humor and vitreous body",
"营养路径：外界external environment→消化系统digestive system→血浆→心血管cardiovascular运输→穿过毛细血管壁capillary wall→组织液→被细胞摄取。废物反向：CO2经呼吸respiratory排出，含氮废物nitrogenous wastes经泌尿urinary排出",
"稳态干扰：外部（高温high temperature、缺氧lack of oxygen）· 内部（低血糖low blood glucose）· 心理压力psychological stress。调节主力：神经（action potentials，快）+内分泌（hormones，慢）",
"反馈三组件：receptor（感受器，经 afferent pathway 传入，af-=朝向）→ control center（控制中枢，设调定点，经 efferent pathway 传出，ef-=离开）→ effector（效应器，产生反应；几乎所有器官组织都可作效应器）",
"负反馈=逆转变化：血压升高→baroreceptor压力感受器→脑→心率减慢decreased heart rate+血管舒张vasodilation→血压回降。随恢复自动减弱停止；调节长期稳定的条件",
"正反馈=加强变化：分娩（宫颈牵拉cervical stretching→催产素oxytocin→更强宫缩，胎儿娩出终止）；失血过多（血压降→心肌缺氧→泵血更弱→血压更低）；血液凝固。需外部机制终止，否则run away可致命；调节不常发生的事件",
"disorder=结构或功能任何异常；disease=有明确认知症状体征的疾病；local（鼻窦感染）vs systemic（流感，全身）。symptom=主观症状（头痛），sign=客观体征（发热）"]},
{t:"1.5 解剖学术语", items:[
"标准姿势anatomical position：直立stand erect、头平视正前方head level & eyes forward、双足平行向前feet flat & directed forward、上肢垂于体侧upper limbs at sides、手掌向前palms forward。prone=俯卧，supine=仰卧",
"区域名称（Fig 1.6重点）：cephalic头·cervical颈·thoracic胸·abdominal腹·pelvic盆；brachial臂·antebrachial前臂·carpal腕；femoral股·patellar髌·crural小腿·tarsal踝·pedal足；axillary腋·inguinal腹股沟·gluteal臀·umbilical脐。临床高频：sternal胸骨·antecubital肘前·olecranal肘后·popliteal腘（膝后）·coxal髋·pubic耻·lumbar腰·sacral骶·perineal会阴·scapular肩胛·palmar掌·plantar足底·occipital枕",
"方位术语（成对）：superior/inferior（上下）、anterior/posterior（前后，人=ventral/dorsal）、medial/lateral（内外侧）、proximal/distal（远近端）、superficial/deep（深浅）；intermediate（之间）、ipsilateral（同侧）、contralateral（对侧）",
"切面：sagittal（矢状；过中线均分左右称midsagittal/median plane，不过中线称parasagittal）· frontal/coronal（额状/冠状，分前后）· transverse（横切=horizontal，分上下）· oblique（斜切）。section=沿切面切开；三切面互相垂直",
"体腔：cranial（brain脑，三层meninges脑膜保护，与椎管相通）· vertebral canal（spinal cord脊髓）；thoracic含pleural×2（lungs肺，潜在腔potential space）· pericardial（heart心）· mediastinum（纵隔：heart心、esophagus食管、trachea气管、thymus胸腺、large blood vessels大血管，除肺外）；abdominopelvic=abdominal（stomach胃、spleen脾、liver肝、gallbladder胆、小肠small intestine、大部大肠large intestine）+pelvic（urinary bladder膀胱、部分大肠、生殖器官reproductive organs）。viscera=胸+腹盆腔内脏器",
"浆膜serous membrane：光滑双层、不直接开口于外界；pleura（胸膜）、pericardium（心包）、peritoneum（腹膜）；parietal=衬腔壁，visceral=覆脏器；层间serous fluid润滑。retroperitoneal（腹膜后位）：kidneys肾、adrenal glands肾上腺、pancreas胰、duodenum十二指肠、ascending/descending colons升/降结肠、abdominal aorta腹主动脉、inferior vena cava下腔静脉",
"其他体腔：oral（口）、nasal（鼻）、orbital（眼眶）、middle ear（中耳）、synovial（关节）。腹盆九分区（上→下，右→左）：right hypochondriac右季肋·epigastric上腹·left hypochondriac左季肋；right lumbar右腰·umbilical脐·left lumbar左腰；right inguinal/iliac右腹股沟·hypogastric/pubic下腹/耻·left inguinal/iliac左腹股沟。分界线：subcostal肋下线+transtubercular结节间线+midclavicular锁骨中线。九分区nine regions用于解剖研究，四象限quadrants（median正中线+transumbilical经脐线）用于临床定位疼痛/肿瘤。横切面从下往上看：前在上、身体左侧在图右"]},
{t:"1.6 衰老与稳态 · 1.7 医学影像", items:[
"1.6 衰老：aging=恢复稳态能力进行性下降，各系统结构功能退化，对压力和疾病易感性增加。表现：皱纹wrinkles、白发gray hair、骨量/肌量减少loss of bone & muscle mass、反射减弱diminished reflexes、激素减少decreased hormones、心脏病heart disease/感染infections/癌症cancer易感、肺活量降decreased lung capacity、消化/肾功能降declining digestive & kidney function、绝经menopause、前列腺增大enlarged prostate",
"1.7 医学影像：radiography（最早，1895伦琴，X线；致密=白、含气=黑）· CT（X线断层；CCTA=冠状动脉CT血管成像，图像可旋转放大）· MRI（磁场+无线电波radio waves，无电离辐射，软组织高对比）· ultrasound（声波，无电离辐射，最安全，孕期首选；图像叫sonogram）· PET（正电子，显示功能/代谢）· endoscopy（内窥镜，直视管腔内部，如结肠镜看乙状结肠）"]}
],
quiz:[
{q:"Anatomy is the scientific study of ___.",o:["body functions","body structures and their relationships","the effects of drugs","the causes of disease"],a:1,e:"Anatomy 研究结构，physiology 研究功能。",g:"1.1"},
{q:"Which of the following is NOT one of the six levels of structural organization?",o:["chemical","cellular","atomic","tissue"],a:2,e:"六个层次：chemical → cellular → tissue → organ → system → organismal。",g:"1.2"},
{q:"The breakdown of complex chemical substances into simpler components is called ___.",o:["anabolism","catabolism","homeostasis","differentiation"],a:1,e:"Catabolism=分解（如消化分解蛋白质），anabolism=合成。",g:"1.3"},
{q:"How many basic types of tissues make up the human body?",o:["2","4","6","11"],a:1,e:"四种：epithelial、connective、muscular、nervous。",g:"1.2"},
{q:"Homeostasis is best defined as ___.",o:["the breakdown of nutrients for energy","the maintenance of relatively stable conditions in the internal environment","the division of cells for growth","the response to medical drugs"],a:1,e:"稳态是内环境（ECF）相对稳定的动态平衡。",g:"1.4"},
{q:"In a feedback system, the structure that monitors changes in a controlled condition and sends input to the control center is the ___.",o:["effector","receptor","stimulus","response"],a:1,e:"Receptor 监测变化，经传入通路向控制中枢发送信息。",g:"1.4"},
{q:"The afferent pathway carries information ___.",o:["away from the control center","toward the control center","only to skeletal muscles","only to glands"],a:1,e:"Afferent: af-=朝向，信息流向控制中枢；efferent 则离开。",g:"1.4"},
{q:"Regulation of blood pressure by baroreceptors is an example of ___.",o:["positive feedback","negative feedback","no feedback","feedforward regulation"],a:1,e:"血压升高→心率减慢血管舒张→血压回降，逆转了原变化，为负反馈。",g:"1.4"},
{q:"Which of the following is an example of a positive feedback system?",o:["blood pressure regulation","labor contractions during childbirth","body temperature regulation","blood glucose regulation"],a:1,e:"分娩时宫缩加强宫颈牵拉→更多催产素→更强宫缩，不断加强直至胎儿娩出。",g:"1.4"},
{q:"During childbirth, oxytocin is released by the ___.",o:["thyroid gland","pituitary gland","adrenal gland","pancreas"],a:1,e:"脑（控制中枢）使垂体释放催产素，作用于子宫肌层（效应器）。",g:"1.4"},
{q:"Intracellular fluid (ICF) is ___.",o:["the fluid between cells","the fluid within cells","blood plasma","lymph"],a:1,e:"ICF=intra（内）细胞内液；ECF=细胞外液。",g:"1.4"},
{q:"The fluid that fills the narrow spaces between tissue cells is called ___.",o:["blood plasma","interstitial fluid","cytosol","cerebrospinal fluid"],a:1,e:"组织液 interstitial fluid 是细胞之间的 ECF。",g:"1.4"},
{q:"In the anatomical position, the palms face ___.",o:["backward","forward","medially","downward"],a:1,e:"标准姿势：直立、面向前、双足平行、手掌向前。",g:"1.5"},
{q:"A body lying facedown is in the ___ position.",o:["supine","prone","anatomical","lateral"],a:1,e:"Prone=俯卧（脸朝下），supine=仰卧（脸朝上）。",g:"1.5"},
{q:"The heart is ___ to the liver.",o:["inferior","superior","distal","lateral"],a:1,e:"心脏在肝的上方，superior=朝向头部。",g:"1.5"},
{q:"The sternum (breastbone) is ___ to the heart.",o:["posterior","anterior","deep","superior"],a:1,e:"胸骨在心脏的前方，anterior=近身体前面。",g:"1.5"},
{q:"Which plane divides the body into equal right and left halves?",o:["frontal plane","transverse plane","midsagittal plane","oblique plane"],a:2,e:"Midsagittal=正中矢状面，经过中线均分左右。",g:"1.5"},
{q:"A frontal (coronal) plane divides the body into ___ portions.",o:["superior and inferior","anterior and posterior","right and left","proximal and distal"],a:1,e:"额状面/冠状面将身体分为前（anterior）后（posterior）两部分。",g:"1.5"},
{q:"A transverse plane divides the body into ___ portions.",o:["anterior and posterior","superior and inferior","right and left","medial and lateral"],a:1,e:"横切面（水平面）分为上（superior）下（inferior）两部分。",g:"1.5"},
{q:"The heart is located in the ___.",o:["pleural cavity","pericardial cavity","abdominal cavity","pelvic cavity"],a:1,e:"心包腔 pericardial cavity 包绕心脏；胸膜腔包绕肺。",g:"1.5"},
{q:"Physiology is the science of body structures.",t:"tf",a:1,e:"这是 anatomy 的定义；physiology 研究身体功能。",g:"1.1"},
{q:"A positive feedback system reverses the original stimulus.",t:"tf",a:1,e:"正反馈是加强（reinforce）原变化；逆转的是负反馈。",g:"1.4"},
{q:"Extracellular fluid serves as the body's internal environment.",t:"tf",a:0,e:"ECF 包围细胞，是内环境；体外空间才是外环境。",g:"1.4"},
{q:"The visceral pleura lines the chest wall.",t:"tf",a:1,e:"衬于腔壁的是 parietal（壁层）；visceral（脏层）贴于肺表面。",g:"1.5"},
{q:"The phalanges (finger bones) are distal to the carpals (wrist bones).",t:"tf",a:0,e:"指骨比腕骨更远离肢体附着处，故为 distal。",g:"1.5"},
{q:"The scientific study of how body parts function is called ___.",o:["anatomy","physiology","histology","pathology"],a:1,e:"Physiology=功能，anatomy=结构。",g:"1.1"},
{q:"Which of the following is an example of physiology?",o:["naming the bones of the skull","explaining how the heart pumps blood","describing the shape of the liver","listing the muscles of the arm"],a:1,e:"解释心脏如何泵血=研究功能，属 physiology。",g:"1.1"},
{q:"Dissection refers to ___.",o:["studying tissues under a microscope","carefully cutting apart body structures to study their relationships","measuring blood pressure","observing a living patient"],a:1,e:"Dissection=小心切开身体结构以研究其相互关系。",g:"1.1"},
{q:"Anatomy and physiology are completely unrelated disciplines.",t:"tf",a:1,e:"两者紧密相关：结构决定功能，功能反映结构。",g:"1.1"},
{q:"Which level of organization consists of groups of similar cells?",o:["chemical","cellular","tissue","organ"],a:2,e:"组织=tissue，由相似细胞组成。",g:"1.2"},
{q:"An organ is composed of ___.",o:["one cell type","two or more tissue types","one tissue type only","only epithelial tissue"],a:1,e:"器官由两种或以上组织类型构成。",g:"1.2"},
{q:"The skin is best classified as a(n) ___.",o:["cell","tissue","organ","organ system"],a:2,e:"皮肤由上皮+结缔+肌肉+神经多种组织构成，是器官。",g:"1.2"},
{q:"In the book analogy of body organization, if cells are words, then tissues are ___.",o:["chapters","paragraphs","the book","the index"],a:1,e:"词→细胞，段落→组织，章节→器官，整书→系统。",g:"1.2"},
{q:"Blood loss from injury causes blood pressure to fall; the body responds by constricting blood vessels to raise it. This is an example of ___ feedback.",o:["positive","negative","neutral","feedforward"],a:1,e:"身体试图逆转血压下降（恢复调定点），是负反馈。",g:"1.4"},
{q:"Which sequence shows the correct order from simplest to most complex?",o:["organ→tissue→cellular→chemical","chemical→cellular→tissue→organ→system→organismal","cellular→chemical→organ→tissue","system→organ→tissue→cellular→chemical"],a:1,e:"化学→细胞→组织→器官→系统→个体。",g:"1.2"},
{q:"The cardiovascular system is an example of the ___ level of organization.",o:["cellular","tissue","organ","system"],a:3,e:"心血管系统=系统 level，由心脏、血管、血液组成。",g:"1.2"},
{q:"The process by which unspecialized cells become specialized is called ___.",o:["metabolism","differentiation","responsiveness","reproduction"],a:1,e:"Differentiation=分化，如干细胞分化为肌细胞。",g:"1.3"},
{q:"The ability to detect and respond to changes in the environment is called ___.",o:["movement","responsiveness","growth","digestion"],a:1,e:"Responsiveness=应激性，如瞳孔遇强光收缩。",g:"1.3"},
{q:"Anabolism and catabolism together constitute ___.",o:["homeostasis","metabolism","differentiation","excretion"],a:1,e:"Metabolism=新陈代谢=合成+分解的总和。",g:"1.3"},
{q:"In a feedback system, the receptor ___.",o:["sets the normal range","monitors changes in the controlled condition","produces the response","carries commands to muscles"],a:1,e:"Receptor=感受器，负责监测受控条件的变化。",g:"1.4"},
{q:"Which component of a feedback system establishes the set point?",o:["receptor","control center","effector","afferent pathway"],a:1,e:"控制中枢（如脑）设定调定点并发出指令。",g:"1.4"},
{q:"Blood plasma is classified as ___.",o:["intracellular fluid","extracellular fluid","interstitial fluid only","cytosol"],a:1,e:"血浆是血管内的 ECF（细胞外液）。",g:"1.4"},
{q:"Which of the following is an example of positive feedback?",o:["regulation of blood pressure","blood clotting","body temperature control","blood glucose control"],a:1,e:"血凝块形成不断加强自身=正反馈；其余都是负反馈。",g:"1.4"},
{q:"Negative feedback amplifies the original stimulus.",t:"tf",a:1,e:"负反馈逆转原变化；放大的才是正反馈。",g:"1.4"},
{q:"Oxytocin released during childbirth directly stimulates ___.",o:["milk production only","stronger uterine contractions","a drop in blood pressure","slower heart rate"],a:1,e:"催产素促进子宫收缩，收缩又刺激更多催产素释放。",g:"1.4"},
{q:"In negative feedback, the response of the effector ___.",o:["strengthens the stimulus","reverses the change in the controlled condition","has no effect on the stimulus","always requires conscious control"],a:1,e:"效应器的反应逆转受控条件的变化，恢复稳态。",g:"1.4"},
{q:"The wrist is ___ to the elbow.",o:["proximal","distal","medial","superior"],a:1,e:"腕比肘更远离上肢与躯干的连接处，故为 distal。",g:"1.5"},
{q:"Which cavity houses the brain?",o:["vertebral canal","thoracic cavity","cranial cavity","abdominal cavity"],a:2,e:"颅腔 cranial cavity 容纳脑。",g:"1.5"},
{q:"The spinal cord is housed in the ___.",o:["cranial cavity","vertebral canal","pleural cavity","pericardial cavity"],a:1,e:"椎管 vertebral canal 容纳脊髓。",g:"1.5"},
{q:"The diaphragm separates the ___ cavities.",o:["cranial and vertebral","thoracic and abdominopelvic","pleural and pericardial","abdominal and pelvic"],a:1,e:"膈分隔胸腔与腹盆腔。",g:"1.5"},
{q:"The parietal pleura ___.",o:["covers the lung surface","lines the chest wall","surrounds the heart","lines the abdominal wall"],a:1,e:"壁层 parietal 衬于腔壁；脏层 visceral 才贴于肺表面。",g:"1.5"},
{q:"The appendix is located in the ___.",o:["right upper quadrant","left upper quadrant","right lower quadrant","left lower quadrant"],a:2,e:"阑尾在右下腹 RLQ（麦氏点所在象限）。",g:"1.5"},
{q:"The prone position means lying face up.",t:"tf",a:1,e:"Prone=俯卧（脸朝下）；supine=仰卧（脸朝上）。",g:"1.5"},
{q:"A scientist studying the effects of a new blood pressure drug on kidney function is practicing ___.",o:["pharmacology","pathophysiology","epidemiology","histology"],a:0,e:"Pharmacology=药理学（药物作用）；pathophysiology=病理生理学；epidemiology=流行病学。形近词，Wiley最爱考。",g:"1.1"},
{q:"A patient reports nausea while the nurse measures a fever of 39°C. The nausea is a ___, and the fever is a ___.",o:["sign; symptom","symptom; sign","disorder; disease","symptom; disorder"],a:1,e:"主观感受=symptom（恶心）；客观可测=sign（39°C发烧）。",g:"1.1"},
{q:"A researcher observes that a drug lowers blood pressure, then designs an experiment to test this specific prediction. This approach is called ___.",o:["hypothesis-based science","descriptive science","pseudoscience","theoretical science"],a:0,e:"从具体假说出发再检验=hypothesis-based science；检验过程用演绎推理 deductive reasoning。",g:"1.1"},
{q:"During an operation on the digestive tract, a surgeon sutures the stomach wall. As a structural unit, the stomach belongs to the ___ level of organization.",o:["tissue","organ","system","cellular"],a:1,e:"胃是一个器官（organ）；它和肠同属消化系统，但题问的是胃本身的层级。",g:"1.2"},
{q:"A sheet of cells lining the stomach is at the ___ level, while the stomach itself is at the ___ level.",o:["tissue; organ","organ; system","cellular; tissue","chemical; cellular"],a:0,e:"细胞群=组织（tissue），胃=器官（organ）。Wiley喜欢一次考两个空。",g:"1.2"},
{q:"Smooth muscle tissue, cardiac muscle tissue, and skeletal muscle tissue are all examples of the ___ level.",o:["chemical","tissue","organ","system"],a:1,e:"三种肌组织都是组织层级——考你透过具体例子看层级。",g:"1.2"},
{q:"When you sprint to catch a bus, which two life processes are most directly involved?",o:["movement and responsiveness","growth and reproduction","differentiation and metabolism","reproduction and growth"],a:0,e:"看到车（responsiveness应激）+跑起来（movement运动）。",g:"1.3"},
{q:"A cut on your finger closes up over several days. This healing primarily demonstrates ___.",o:["growth","responsiveness","movement","reproduction"],a:0,e:"伤口愈合=细胞增殖修复=生长（growth）；reproduction指产生后代，别混。",g:"1.3"},
{q:"Shivering when cold and sweating when hot both demonstrate ___.",o:["responsiveness","differentiation","reproduction","growth"],a:0,e:"寒战/出汗都是对外界变化的应答=responsiveness。",g:"1.3"},
{q:"In the baroreceptor reflex, the brain acts as the ___.",o:["receptor","control center","effector","stimulus"],a:1,e:"脑接收传入信息并决定反应=控制中枢；压力感受器才是receptor。",g:"1.4"},
{q:"In blood pressure regulation, impulses traveling from the brain toward the heart are best described as ___.",o:["sensory input","motor output","receptor activity","a stimulus"],a:1,e:"从中枢发出的=传出=output；朝向中枢的=传入=input。记住：afferent进，efferent出。",g:"1.4"},
{q:"In severe hemorrhage, falling blood pressure reduces blood flow to the heart itself, weakening contractions and dropping pressure even further. This self-reinforcing cycle is ___.",o:["negative feedback","positive feedback","homeostatic compensation","acclimatization"],a:1,e:"变化被不断加强=正反馈（恶性循环）；正常代偿升压才是负反馈。",g:"1.4"},
{q:"Which imaging technique uses no ionizing radiation and is preferred during pregnancy?",o:["radiography","computed tomography","ultrasound","positron emission tomography"],a:2,e:"超声用声波无辐射，孕期首选；X线/CT/PET都有电离辐射。",g:"1.7"},
{q:"A physician wants a high-contrast image of the brain's soft tissue. The best choice is ___.",o:["radiography","MRI","ultrasound","endoscopy"],a:1,e:"MRI=软组织高对比度；X线看骨；超声看不清颅内细节。",g:"1.7"},
{q:"In a radiograph, air-filled lungs appear ___.",o:["white","black","gray","invisible"],a:1,e:"X光片：致密结构=白（骨），含气结构=黑（肺）。",g:"1.7"},
{q:"The image produced by an ultrasound examination is called a ___.",o:["radiograph","sonogram","tomogram","scintigram"],a:1,e:"Sonogram=超声图像；radiograph=X光片；tomogram=断层图。",g:"1.7"},
{q:"MRI produces images by using ___.",o:["X-rays","radio waves and magnetic fields","sound waves","gamma rays"],a:1,e:"MRI用磁场+无线电波，不用电离辐射；X线是radiography/CT，声波是ultrasound。",g:"1.7"},
{q:"Which statement about CCTA (coronary computed tomography angiography) is INCORRECT?",o:["it visualizes coronary arteries","the image can be rotated and enlarged","it uses X-rays","the image cannot be rotated or enlarged"],a:3,e:"CCTA图像可以旋转放大看冠状动脉；说'不能旋转放大'是错的。",g:"1.7"},
{q:"To view the interior of the sigmoid colon, the best choice is ___.",o:["ultrasound","endoscopy","radiography","MRI"],a:1,e:"Endoscopy=内窥镜直视管腔内部；结肠镜是endoscopy的一种。",g:"1.7"},
{q:"The oldest medical imaging technique is ___.",o:["MRI","ultrasound","radiography","PET"],a:2,e:"Radiography（X线）1895年伦琴发现，是最早的医学影像。",g:"1.7"},
{q:"A nurse describes a wound as 'lateral to the navel.' The wound is ___.",o:["near the midline","away from the midline","above the navel","below the navel"],a:1,e:"Lateral=远离中线。Wiley场景题：护士描述伤口位置。",g:"1.5"},
{q:"The elbow is ___ to the wrist, and the wrist is ___ to the elbow.",o:["distal; proximal","proximal; distal","medial; lateral","superior; inferior"],a:1,e:"肘近躯干=proximal，腕远躯干=distal——一对互逆放一起考。",g:"1.5"},
{q:"A surgeon makes a cut that separates the body into front and back portions. The cut follows a ___ plane.",o:["sagittal","frontal (coronal)","transverse","midsagittal"],a:1,e:"分前后=额状面；分左右=矢状面；分上下=横切面。场景化考切面。",g:"1.5"},
{q:"The urinary bladder is located in the ___ cavity.",o:["thoracic","cranial","pelvic","abdominal"],a:2,e:"膀胱在盆腔 pelvic cavity；腹腔 abdominal 在上，盆腔在下，同属腹盆腔。",g:"1.5"},
{q:"Which of the following statements about the peritoneum is INCORRECT?",o:["It is the largest serous membrane","The parietal peritoneum lines the abdominal wall","The visceral peritoneum covers abdominal organs","It lines the pleural cavities"],a:3,e:"腹膜 peritoneum 只在腹盆腔；胸膜腔由胸膜 pleura 衬。找错题。",g:"1.5"},
{q:"Which branch of anatomy studies the microscopic structure of tissues?",o:["Histology","Gross anatomy","Embryology","Regional anatomy"],a:0,e:"Histology=组织学（显微镜下看组织）；gross anatomy=肉眼解剖。",g:"1.1"},
{q:"Which tissue type carries information from one part of the body to another through nerve impulses?",o:["Epithelial tissue","Connective tissue","Muscular tissue","Nervous tissue"],a:3,e:"Nervous tissue经神经冲动传递信息；muscular收缩产热；epithelial覆盖衬里；connective连接支持。",g:"1.2"},
{q:"In auscultation, the examiner ___.",o:["observes the body for changes","feels body surfaces with the hands","listens to body sounds, often with a stethoscope","taps the body surface and listens"],a:2,e:"Auscultation=听诊（听）；palpation=触诊（摸）；percussion=叩诊（叩）；inspection=视诊（看）。",g:"1.3"},
{q:"Percussion can help distinguish ___.",o:["hollow cavities from solid organs","arteries from veins","bones from cartilage","nerves from muscles"],a:0,e:"叩诊：空腔与实心器官声音不同，还可判断大小、质地、位置。",g:"1.3"},
{q:"A sinus infection is an example of a ___ disease.",o:["systemic","local","objective","subjective"],a:1,e:"Local=局限一处（鼻窦感染）；systemic=累及全身（流感）。",g:"1.4"},
{q:"Which statement about positive feedback is TRUE?",o:["It reverses the original stimulus","It slows and stops as balance is restored","It must be shut off by some outside mechanism or it may run away","It regulates conditions that stay stable for long periods"],a:2,e:"正反馈不断加强变化，需外部机制终止，否则失控可致命；逆转/自动停止的是负反馈。",g:"1.4"},
{q:"The anatomical term for the armpit is ___.",o:["brachial","axillary","antecubital","inguinal"],a:1,e:"Axillary=腋；brachial=臂；antecubital=肘前；inguinal=腹股沟。Fig 1.6区域名是必学。",g:"1.5"},
{q:"A parasagittal plane divides the body into ___.",o:["equal right and left portions","anterior and posterior portions","superior and inferior portions","unequal right and left portions"],a:3,e:"Parasagittal（para-=旁边）不过中线，分不等左右；过中线均分才是midsagittal。",g:"1.5"},
{q:"The meninges are ___.",o:["three layers of protective tissue around the brain and spinal cord","the membranes lining the pleural cavities","fluid-filled spaces around the heart","bones forming the cranial cavity"],a:0,e:"Meninges=脑和脊髓外三层保护膜+缓冲液；颅腔与椎管相通。",g:"1.5"},
{q:"Which of the following organs is retroperitoneal?",o:["Stomach","Liver","Kidney","Spleen"],a:2,e:"腹膜后位：肾、肾上腺、胰、十二指肠、升/降结肠。胃肝脾都在腹膜内。",g:"1.5"},
{q:"Aging is characterized by ___.",o:["an increased ability to restore homeostasis","a progressive decline in the body's ability to restore homeostasis","a complete loss of all feedback systems","no observable changes in body systems"],a:1,e:"衰老=恢复稳态能力进行性下降，各系统退化，对压力疾病更易感。",g:"1.6"},
{q:"The liver is mostly located in the ___ region.",o:["hypogastric","epigastric","right lumbar","left inguinal"],a:1,e:"肝大部位于上腹区 epigastric（九分区中央上部）。",g:"1.5"},
{q:"The urinary bladder is located in the ___ region.",o:["epigastric","umbilical","hypogastric","right hypochondriac"],a:2,e:"膀胱位于下腹区 hypogastric（九分区中央下部）。",g:"1.5"},
{q:"The ascending colon is located in the ___ region.",o:["left lumbar","right lumbar","epigastric","hypogastric"],a:1,e:"升结肠位于右腰区 right lumbar。教材图题1.13原题。",g:"1.5"}
],
feynman:[
{q:"用自己的话讲清楚：anatomy 和 physiology 各研究什么？为什么说结构决定功能（举 1-2 个例子）？再说出至少 3 个解剖学分支和 2 个生理学分支。",
 points:["anatomy=身体结构及其相互关系（dissection切开研究）；physiology=身体功能（各部分如何工作）","结构决定功能：颅骨紧密保护脑、指骨松散连接便活动、肺泡壁极薄利气体交换","解剖分支：gross / histology组织学 / embryology胚胎学 / pathological / radiographic影像解剖","生理分支：neuro / endocrine / cardiovascular / respiratory / renal 等","pharmacology=药物作用与治疗；epidemiology=疾病在人群中的发生传播"]},
{q:"从简单到复杂说出六个结构层次。解释 chemical 层和 cellular 层的要点，说出四种基本组织的功能，并解释为什么胃属于 organ 层。",
 points:["顺序：chemical → cellular → tissue → organ → system → organismal","chemical：atom最小物质单位，molecule=2+原子；必需元素C/H/O/N/P/Ca/S","cellular：细胞是最小生命单位","四种组织：epithelial覆盖/衬里/成腺；connective连接支持保护；muscular收缩产热；nervous传信息","胃=organ：两种以上组织（外上皮+结缔、3层平滑肌、内上皮）","胰腺横跨消化+内分泌两系统；细胞学说（Wiley补充）：一切生物由细胞组成"]},
{q:"说出六大生命活动。对 metabolism、responsiveness、differentiation 各举一个具体例子，并解释 reproduction 的两层含义。",
 points:["六个：metabolism / responsiveness / movement / growth / differentiation / reproduction","metabolism=catabolism分解+anabolism合成（如蛋白质→氨基酸→新蛋白）","responsiveness：神经细胞→action potentials，肌细胞→收缩","differentiation：干细胞→特化细胞（如红骨髓前体→红/白细胞）","movement四个层次：全身/器官/细胞/细胞内","reproduction：新细胞（修复）或 新个体（受精→zygote）"]},
{q:"说出四种非侵入性诊断技术并用一句话区分。什么是 autopsy？hypothesis-based science 的研究流程是怎样的？",
 points:["inspection视诊（看）/ palpation触诊（摸）/ auscultation听诊（听）/ percussion叩诊（叩听音）","autopsy=死后尸检：确认死因、发现未检出疾病","死亡三指征：心跳停、无自主呼吸、脑功能丧失","hypothesis-based science：从具体假说出发设计实验检验","用 deductive reasoning；证据不支持→修改假说再实验"]},
{q:"什么是 homeostasis？ECF 包括哪六种体液？讲出营养物质从外界到达细胞的完整路径。身体靠哪两大系统调节稳态，各有什么特点？",
 points:["homeostasis=内环境internal environment相对稳定的动态平衡","ECF：组织液、血浆、淋巴、脑脊液、滑液、房水玻璃体","路径：外界→消化系统→血浆→心血管→毛细血管壁→组织液→细胞","废物：CO2经呼吸、含氮废物经泌尿排出","干扰：外部（高温缺氧）/内部（低血糖）/心理压力","神经（action potentials，快）+内分泌（hormones，慢）"]},
{q:"请用自己的话解释什么是负反馈系统，并以血压调节为例，说出三个组件分别是什么、信息如何流动。",
 points:["说出受控条件/刺激的定义","三个组件：receptor → control center → effector","传入 afferent（朝向中枢）/传出 efferent（离开中枢）","血压例子：baroreceptor 感知→脑→心率减慢+血管舒张","点出'逆转了原变化'所以叫负反馈"]},
{q:"解释正反馈系统，并以分娩为例说明循环如何加强、何时终止。再举一个书中的正反馈例子。",
 points:["正反馈=加强/强化原变化","分娩链条：宫缩→宫颈牵拉→催产素→更强宫缩","终止机制：胎儿娩出，牵拉停止","另一个例子：失血过多或血液凝固","点出正反馈若不终止可致命"]},
{q:"区分 disorder / disease / local disease / systemic disease / symptom / sign，每组各举一个例子。",
 points:["disorder=结构或功能任何异常；disease=有明确认知症状体征的疾病","local=局限一处（如鼻窦感染）；systemic=累及全身（如流感）","symptom=主观症状（如头痛、恶心）；sign=客观体征（如发热39°C）","能举出每组至少一个正确例子"]},
{q:"描述解剖学标准姿势。说出至少 8 个身体区域的解剖学名。用三对方位术语举例说明器官相对位置。",
 points:["标准姿势：直立、头平视、双足平行向前、上肢垂体侧、手掌向前","prone=俯卧，supine=仰卧","区域名如：cephalic头、cervical颈、brachial臂、carpal腕、femoral股、patellar髌、axillary腋、inguinal腹股沟","方位术语成对：superior/inferior、anterior/posterior、proximal/distal等","举例：心在肝上方superior；胸骨在心前方anterior；指骨在腕骨远端distal"]},
{q:"说出四种切面及各自分开的部分。体腔有哪几个？浆膜的两层分别叫什么、位置在哪？九分区和四象限各用于什么场景？",
 points:["sagittal分左右（过中线=midsagittal，不过=parasagittal）；frontal分前后；transverse分上下；oblique斜切","section=沿切面切开；三切面互相垂直","cranial（脑+meninges）/ vertebral canal（脊髓）；thoracic（胸膜腔×2+心包腔+纵隔）；abdominopelvic（腹腔+盆腔）","浆膜：parietal衬腔壁，visceral覆脏器；pleura/pericardium/peritoneum","retroperitoneal举例：肾、胰、十二指肠","九分区nine regions用于解剖研究；四象限quadrants用于临床定位疼痛/肿瘤"]},
{q:"衰老与稳态是什么关系？说出六种医学影像技术，并指出哪种孕期首选、哪种看软组织最清楚。",
 points:["aging=恢复稳态能力进行性下降，各系统退化、易感性增加","表现举例：骨量肌量减少、反射减弱、肺活量降等","radiography最早（X线，致密白/含气黑）；CT断层","MRI软组织高对比；ultrasound无辐射、孕期首选","PET看功能代谢；endoscopy直视体内"]}
]
};;
