// data2.js — Lexi v2 扩展题库
// 说明：
// - SENTENCES2：280 条句子，4 个类目各 70 条，供“句子练习/填空”等模式使用
//   cat 取值：idioms（地道习语）、spoken（日常口语）、work（工作英语）、emotion（情感话题）
//   每条 {en, zh, cat}，英文 3-15 个词，难度由浅入深
// - GRAMMAR：100 道语法选择题，每条 {q, options, a, tip}
//   q 为带 ____ 的句子；options 为 4 个选项；a 为正确选项下标(0-3)；tip 为中文考点讲解
// 用法：与 data.js 一起引入，SENTENCES2 / GRAMMAR 为全局变量
var SENTENCES2 = [];
var GRAMMAR = [];

// ============ idioms：地道英语表达（70 条） ============
SENTENCES2.push({en:"Break a leg!", zh:"祝你好运！（演出前常用的祝福语，并非诅咒）", cat:"idioms"});
SENTENCES2.push({en:"It's raining cats and dogs.", zh:"外面下着倾盆大雨。", cat:"idioms"});
SENTENCES2.push({en:"That test was a piece of cake.", zh:"那场考试小菜一碟。", cat:"idioms"});
SENTENCES2.push({en:"I'm feeling under the weather.", zh:"我觉得身体有点不舒服。", cat:"idioms"});
SENTENCES2.push({en:"Let's hit the road.", zh:"咱们出发吧。", cat:"idioms"});
SENTENCES2.push({en:"She has butterflies in her stomach.", zh:"她紧张得心里七上八下。", cat:"idioms"});
SENTENCES2.push({en:"Don't beat around the bush.", zh:"别拐弯抹角，直说吧。", cat:"idioms"});
SENTENCES2.push({en:"He spilled the beans.", zh:"他把秘密说漏嘴了。", cat:"idioms"});
SENTENCES2.push({en:"It's not rocket science.", zh:"这又不是什么难事。", cat:"idioms"});
SENTENCES2.push({en:"We're on the same page.", zh:"我们的想法一致。", cat:"idioms"});
SENTENCES2.push({en:"That costs an arm and a leg.", zh:"那东西贵得离谱。", cat:"idioms"});
SENTENCES2.push({en:"I'll catch up with you later.", zh:"我晚点再找你。", cat:"idioms"});
SENTENCES2.push({en:"He's pulling my leg.", zh:"他在跟我开玩笑。", cat:"idioms"});
SENTENCES2.push({en:"Let's call it a day.", zh:"今天就到这儿吧。", cat:"idioms"});
SENTENCES2.push({en:"I'm all ears.", zh:"我洗耳恭听。", cat:"idioms"});
SENTENCES2.push({en:"She hit the nail on the head.", zh:"她一语中的。", cat:"idioms"});
SENTENCES2.push({en:"Don't count your chickens yet.", zh:"别高兴得太早。", cat:"idioms"});
SENTENCES2.push({en:"It's a blessing in disguise.", zh:"这是因祸得福。", cat:"idioms"});
SENTENCES2.push({en:"He kicked the bucket.", zh:"他去世了。（委婉说法）", cat:"idioms"});
SENTENCES2.push({en:"Let's get the ball rolling.", zh:"咱们开始行动吧。", cat:"idioms"});
SENTENCES2.push({en:"I'm on cloud nine.", zh:"我开心极了。", cat:"idioms"});
SENTENCES2.push({en:"That rings a bell.", zh:"这听起来有点耳熟。", cat:"idioms"});
SENTENCES2.push({en:"Don't put all your eggs in one basket.", zh:"别把赌注全押在一处。", cat:"idioms"});
SENTENCES2.push({en:"She's the apple of his eye.", zh:"她是他的掌上明珠。", cat:"idioms"});
SENTENCES2.push({en:"It's time to face the music.", zh:"该面对现实、承担后果了。", cat:"idioms"});
SENTENCES2.push({en:"He let the cat out of the bag.", zh:"他泄露了秘密。", cat:"idioms"});
SENTENCES2.push({en:"I'm in hot water.", zh:"我惹上麻烦了。", cat:"idioms"});
SENTENCES2.push({en:"Let's bite the bullet.", zh:"咱们咬牙挺过去吧。", cat:"idioms"});
SENTENCES2.push({en:"She's feeling blue today.", zh:"她今天心情低落。", cat:"idioms"});
SENTENCES2.push({en:"That was a close call.", zh:"那真是千钧一发。", cat:"idioms"});
SENTENCES2.push({en:"Don't cry over spilled milk.", zh:"事已至此，别再懊悔了。", cat:"idioms"});
SENTENCES2.push({en:"He's a night owl.", zh:"他是个夜猫子。", cat:"idioms"});
SENTENCES2.push({en:"Let's play it by ear.", zh:"咱们随机应变吧。", cat:"idioms"});
SENTENCES2.push({en:"I'm snowed under with work.", zh:"我工作堆积如山。", cat:"idioms"});
SENTENCES2.push({en:"She bent over backwards to help.", zh:"她竭尽全力帮忙。", cat:"idioms"});
SENTENCES2.push({en:"That idea went down the drain.", zh:"那个想法泡汤了。", cat:"idioms"});
SENTENCES2.push({en:"He's got cold feet.", zh:"他临阵退缩了。", cat:"idioms"});
SENTENCES2.push({en:"Let's cut to the chase.", zh:"咱们直奔主题吧。", cat:"idioms"});
SENTENCES2.push({en:"I'm at the end of my rope.", zh:"我已经忍无可忍了。", cat:"idioms"});
SENTENCES2.push({en:"That joke fell flat.", zh:"那个笑话没人觉得好笑。", cat:"idioms"});
SENTENCES2.push({en:"She's sitting on the fence.", zh:"她还在犹豫不决。", cat:"idioms"});
SENTENCES2.push({en:"Don't bite off more than you can chew.", zh:"别贪多嚼不烂。", cat:"idioms"});
SENTENCES2.push({en:"He's barking up the wrong tree.", zh:"他找错对象了，方向搞错了。", cat:"idioms"});
SENTENCES2.push({en:"Let's burn the midnight oil.", zh:"咱们熬夜赶工吧。", cat:"idioms"});
SENTENCES2.push({en:"I'm over the moon.", zh:"我欣喜若狂。", cat:"idioms"});
SENTENCES2.push({en:"That news hit me like a ton of bricks.", zh:"那个消息让我大受打击。", cat:"idioms"});
SENTENCES2.push({en:"She's got a heart of gold.", zh:"她心地善良。", cat:"idioms"});
SENTENCES2.push({en:"Let's cross that bridge later.", zh:"船到桥头自然直，以后再说。", cat:"idioms"});
SENTENCES2.push({en:"He's in the same boat.", zh:"他处境相同，感同身受。", cat:"idioms"});
SENTENCES2.push({en:"Don't judge a book by its cover.", zh:"别以貌取人。", cat:"idioms"});
SENTENCES2.push({en:"I'm walking on eggshells around him.", zh:"我在他面前小心翼翼。", cat:"idioms"});
SENTENCES2.push({en:"That put me in a good mood.", zh:"那让我心情大好。", cat:"idioms"});
SENTENCES2.push({en:"She's burning the candle at both ends.", zh:"她过度操劳，身体快吃不消了。", cat:"idioms"});
SENTENCES2.push({en:"Let's not jump to conclusions.", zh:"咱们别急着下结论。", cat:"idioms"});
SENTENCES2.push({en:"He's a fish out of water.", zh:"他在新环境里很不适应。", cat:"idioms"});
SENTENCES2.push({en:"I'm keeping my fingers crossed.", zh:"我在默默祈祷好运。", cat:"idioms"});
SENTENCES2.push({en:"That story sounds fishy.", zh:"那个说法听起来很可疑。", cat:"idioms"});
SENTENCES2.push({en:"She's the black sheep of the family.", zh:"她是家里的“异类”。", cat:"idioms"});
SENTENCES2.push({en:"Take it with a grain of salt.", zh:"对这话别全信，半信半疑就好。", cat:"idioms"});
SENTENCES2.push({en:"He's beating a dead horse.", zh:"他在做无用功。", cat:"idioms"});
SENTENCES2.push({en:"I'm down in the dumps.", zh:"我情绪很低落。", cat:"idioms"});
SENTENCES2.push({en:"That really took the cake!", zh:"这也太离谱了！（表示吃惊或不满）", cat:"idioms"});
SENTENCES2.push({en:"She's got ants in her pants.", zh:"她坐立不安。", cat:"idioms"});
SENTENCES2.push({en:"Give him the benefit of the doubt.", zh:"姑且相信他这一次吧。", cat:"idioms"});
SENTENCES2.push({en:"I'm on thin ice.", zh:"我的处境很危险。", cat:"idioms"});
SENTENCES2.push({en:"That was music to my ears.", zh:"那正是我想听到的。", cat:"idioms"});
SENTENCES2.push({en:"He's going down a rabbit hole.", zh:"他越陷越深，钻牛角尖了。", cat:"idioms"});
SENTENCES2.push({en:"Let's put our heads together.", zh:"咱们集思广益吧。", cat:"idioms"});
SENTENCES2.push({en:"I've been barking orders all day.", zh:"我整天都在发号施令，快累坏了。", cat:"idioms"});
SENTENCES2.push({en:"She's walking on air.", zh:"她高兴得飘飘然。", cat:"idioms"});

// ============ spoken：日常口语（70 条） ============
SENTENCES2.push({en:"Hey, what's up with you?", zh:"最近怎么样？", cat:"spoken"});
SENTENCES2.push({en:"Man, I'm totally beat today.", zh:"我累坏了。", cat:"spoken"});
SENTENCES2.push({en:"No worries at all.", zh:"没关系，别放在心上。", cat:"spoken"});
SENTENCES2.push({en:"Hang on a sec.", zh:"稍等一下。", cat:"spoken"});
SENTENCES2.push({en:"That sounds awesome!", zh:"听起来太棒了！", cat:"spoken"});
SENTENCES2.push({en:"I'm absolutely starving right now.", zh:"我饿坏了。", cat:"spoken"});
SENTENCES2.push({en:"Long time no see!", zh:"好久不见！", cat:"spoken"});
SENTENCES2.push({en:"Oops, my bad.", zh:"我的错。", cat:"spoken"});
SENTENCES2.push({en:"That works for me.", zh:"我这边没问题。", cat:"spoken"});
SENTENCES2.push({en:"I'm down for pizza.", zh:"吃披萨我没问题。", cat:"spoken"});
SENTENCES2.push({en:"No way, that's crazy!", zh:"不会吧！/ 没门！", cat:"spoken"});
SENTENCES2.push({en:"Just chill out, okay?", zh:"冷静点，放轻松。", cat:"spoken"});
SENTENCES2.push({en:"What's the deal?", zh:"什么情况？", cat:"spoken"});
SENTENCES2.push({en:"I'm running late.", zh:"我要迟到了。", cat:"spoken"});
SENTENCES2.push({en:"That was epic!", zh:"那太精彩了！", cat:"spoken"});
SENTENCES2.push({en:"Are you being serious?", zh:"真的吗？", cat:"spoken"});
SENTENCES2.push({en:"I'm good, thanks.", zh:"我挺好的，谢谢。", cat:"spoken"});
SENTENCES2.push({en:"Catch you later!", zh:"回头见！", cat:"spoken"});
SENTENCES2.push({en:"That's so cool.", zh:"太酷了。", cat:"spoken"});
SENTENCES2.push({en:"I'm freaking out.", zh:"我快崩溃了。", cat:"spoken"});
SENTENCES2.push({en:"Whatever works for you.", zh:"怎么都行。", cat:"spoken"});
SENTENCES2.push({en:"Mind if I join?", zh:"我可以加入吗？", cat:"spoken"});
SENTENCES2.push({en:"That hit the spot.", zh:"这正合我意。（吃喝满足时说）", cat:"spoken"});
SENTENCES2.push({en:"I'm so over this.", zh:"我受够这个了。", cat:"spoken"});
SENTENCES2.push({en:"You nailed it!", zh:"你做得太完美了！", cat:"spoken"});
SENTENCES2.push({en:"Let's grab coffee.", zh:"咱们去喝杯咖啡吧。", cat:"spoken"});
SENTENCES2.push({en:"I'm totally lost.", zh:"我完全懵了。", cat:"spoken"});
SENTENCES2.push({en:"Okay, fair enough then.", zh:"有道理，行吧。", cat:"spoken"});
SENTENCES2.push({en:"That made my day.", zh:"这让我一整天都开心。", cat:"spoken"});
SENTENCES2.push({en:"I'm on my way.", zh:"我在路上了。", cat:"spoken"});
SENTENCES2.push({en:"No big deal.", zh:"小事一桩。", cat:"spoken"});
SENTENCES2.push({en:"What's going on?", zh:"发生什么事了？", cat:"spoken"});
SENTENCES2.push({en:"I'm hooked on this show.", zh:"我迷上这部剧了。", cat:"spoken"});
SENTENCES2.push({en:"Take your time.", zh:"慢慢来，不着急。", cat:"spoken"});
SENTENCES2.push({en:"That was a blast!", zh:"那太好玩了！", cat:"spoken"});
SENTENCES2.push({en:"I'm dead tired.", zh:"我累死了。", cat:"spoken"});
SENTENCES2.push({en:"You got this!", zh:"你能行！", cat:"spoken"});
SENTENCES2.push({en:"Let's chill tonight.", zh:"今晚放松一下吧。", cat:"spoken"});
SENTENCES2.push({en:"I'm craving ice cream.", zh:"我特别想吃冰淇淋。", cat:"spoken"});
SENTENCES2.push({en:"That cracked me up.", zh:"那把我逗笑了。", cat:"spoken"});
SENTENCES2.push({en:"No kidding, really?", zh:"真的假的！", cat:"spoken"});
SENTENCES2.push({en:"I'm all set.", zh:"我准备好了。", cat:"spoken"});
SENTENCES2.push({en:"So, what's new today?", zh:"最近有啥新鲜事？", cat:"spoken"});
SENTENCES2.push({en:"That gave me goosebumps.", zh:"那让我起了一身鸡皮疙瘩。", cat:"spoken"});
SENTENCES2.push({en:"I'm winging it.", zh:"我即兴发挥呢。", cat:"spoken"});
SENTENCES2.push({en:"That was a good call!", zh:"好主意！", cat:"spoken"});
SENTENCES2.push({en:"I just zoned out.", zh:"我刚才走神了。", cat:"spoken"});
SENTENCES2.push({en:"Okay, let's bounce now.", zh:"咱们撤吧。", cat:"spoken"});
SENTENCES2.push({en:"Wow, that's really lit!", zh:"太燃了！", cat:"spoken"});
SENTENCES2.push({en:"I'm low-key excited.", zh:"我有点小激动。", cat:"spoken"});
SENTENCES2.push({en:"Spill the tea!", zh:"快说说八卦！", cat:"spoken"});
SENTENCES2.push({en:"That song slaps!", zh:"这首歌太好听了！", cat:"spoken"});
SENTENCES2.push({en:"I'm vibing with this song.", zh:"我超爱这首歌的氛围。", cat:"spoken"});
SENTENCES2.push({en:"Bet, see you then!", zh:"一言为定！", cat:"spoken"});
SENTENCES2.push({en:"Hmm, that's kind of sus.", zh:"那很可疑。", cat:"spoken"});
SENTENCES2.push({en:"I'm ghosting my phone today.", zh:"我今天不想碰手机。", cat:"spoken"});
SENTENCES2.push({en:"Let's do brunch.", zh:"咱们去吃早午餐吧。", cat:"spoken"});
SENTENCES2.push({en:"I'm wiped out.", zh:"我精疲力尽了。", cat:"spoken"});
SENTENCES2.push({en:"That was clutch!", zh:"关键时刻太给力了！", cat:"spoken"});
SENTENCES2.push({en:"No cap, that's amazing.", zh:"说真的，那太厉害了。", cat:"spoken"});
SENTENCES2.push({en:"I'm in my feels.", zh:"我有点多愁善感。", cat:"spoken"});
SENTENCES2.push({en:"Let's link up soon.", zh:"咱们最近约一下。", cat:"spoken"});
SENTENCES2.push({en:"That's a vibe.", zh:"那感觉太对了。", cat:"spoken"});
SENTENCES2.push({en:"I'm booked this weekend.", zh:"我这周末有安排了。", cat:"spoken"});
SENTENCES2.push({en:"Honestly, big mood.", zh:"太真实了，深有同感。", cat:"spoken"});
SENTENCES2.push({en:"Let's keep it low-key.", zh:"咱们低调点。", cat:"spoken"});
SENTENCES2.push({en:"I'm here for it!", zh:"我全力支持！", cat:"spoken"});
SENTENCES2.push({en:"Honestly, that's just facts.", zh:"说得太对了。", cat:"spoken"});
SENTENCES2.push({en:"Let's run it back.", zh:"咱们再来一次。", cat:"spoken"});
SENTENCES2.push({en:"I'm out of the loop.", zh:"我跟不上情况了。", cat:"spoken"});

// ============ work：工作英语（70 条） ============
SENTENCES2.push({en:"Let's circle back tomorrow.", zh:"咱们明天再跟进讨论。", cat:"work"});
SENTENCES2.push({en:"Could you loop me in?", zh:"能让我也参与/知情吗？", cat:"work"});
SENTENCES2.push({en:"The deadline is tight.", zh:"截止日期很紧。", cat:"work"});
SENTENCES2.push({en:"I'll send over the report.", zh:"我会把报告发过去。", cat:"work"});
SENTENCES2.push({en:"Let's touch base next week.", zh:"咱们下周碰一下。", cat:"work"});
SENTENCES2.push({en:"Please see the attached file.", zh:"请查收附件。", cat:"work"});
SENTENCES2.push({en:"I'll follow up with you.", zh:"我会跟进这件事。", cat:"work"});
SENTENCES2.push({en:"Can we move this meeting?", zh:"能把这个会改期吗？", cat:"work"});
SENTENCES2.push({en:"Let's put this on hold.", zh:"咱们先把这事搁置。", cat:"work"});
SENTENCES2.push({en:"I need an extension.", zh:"我需要延期。", cat:"work"});
SENTENCES2.push({en:"The client approved the proposal.", zh:"客户批准了方案。", cat:"work"});
SENTENCES2.push({en:"Let's brainstorm some ideas.", zh:"咱们头脑风暴一下。", cat:"work"});
SENTENCES2.push({en:"I'll take care of it.", zh:"我来处理。", cat:"work"});
SENTENCES2.push({en:"Please keep me posted.", zh:"请随时告诉我进展。", cat:"work"});
SENTENCES2.push({en:"We're behind schedule.", zh:"我们进度落后了。", cat:"work"});
SENTENCES2.push({en:"Let's set up a call.", zh:"咱们约个电话会议吧。", cat:"work"});
SENTENCES2.push({en:"The budget got approved.", zh:"预算批下来了。", cat:"work"});
SENTENCES2.push({en:"I appreciate your hard work.", zh:"感谢你的辛勤付出。", cat:"work"});
SENTENCES2.push({en:"Let's prioritize this task.", zh:"咱们优先处理这项任务。", cat:"work"});
SENTENCES2.push({en:"I'll get back to you soon.", zh:"我会尽快回复你。", cat:"work"});
SENTENCES2.push({en:"We need to cut costs.", zh:"我们需要削减成本。", cat:"work"});
SENTENCES2.push({en:"The meeting is at nine sharp.", zh:"会议九点准时开始。", cat:"work"});
SENTENCES2.push({en:"Please confirm your attendance.", zh:"请确认你是否参加。", cat:"work"});
SENTENCES2.push({en:"Let's review the numbers.", zh:"咱们核对一下数据。", cat:"work"});
SENTENCES2.push({en:"I have a conflict that afternoon.", zh:"那天下午我有冲突安排。", cat:"work"});
SENTENCES2.push({en:"The project is on track.", zh:"项目进展顺利。", cat:"work"});
SENTENCES2.push({en:"Let's think outside the box.", zh:"咱们跳出思维定式想想。", cat:"work"});
SENTENCES2.push({en:"I'll cc you on the email.", zh:"我会在邮件里抄送你。", cat:"work"});
SENTENCES2.push({en:"We hit our quarterly target.", zh:"我们达成了季度目标。", cat:"work"});
SENTENCES2.push({en:"Please submit it by Friday.", zh:"请在周五前提交。", cat:"work"});
SENTENCES2.push({en:"Let's schedule a one-on-one.", zh:"咱们约个一对一面谈。", cat:"work"});
SENTENCES2.push({en:"The new policy takes effect Monday.", zh:"新政策周一起生效。", cat:"work"});
SENTENCES2.push({en:"I need your sign-off.", zh:"需要你签字批准。", cat:"work"});
SENTENCES2.push({en:"Let's streamline the process.", zh:"咱们优化一下流程。", cat:"work"});
SENTENCES2.push({en:"The team nailed the presentation.", zh:"团队的展示非常出色。", cat:"work"});
SENTENCES2.push({en:"We need more hands on deck.", zh:"我们需要增派人手。", cat:"work"});
SENTENCES2.push({en:"I'll draft the contract today.", zh:"我今天起草合同。", cat:"work"});
SENTENCES2.push({en:"Let's align on the goals.", zh:"咱们先统一目标。", cat:"work"});
SENTENCES2.push({en:"The launch was a success.", zh:"发布很成功。", cat:"work"});
SENTENCES2.push({en:"Please escalate this issue.", zh:"请把这个问题升级上报。", cat:"work"});
SENTENCES2.push({en:"We need to pivot our strategy.", zh:"我们需要调整战略。", cat:"work"});
SENTENCES2.push({en:"I'll block my calendar.", zh:"我会在日历上留出时间。", cat:"work"});
SENTENCES2.push({en:"Let's do a quick sync.", zh:"咱们快速对齐一下。", cat:"work"});
SENTENCES2.push({en:"The invoice is overdue.", zh:"发票逾期了。", cat:"work"});
SENTENCES2.push({en:"Great job on the campaign!", zh:"这次推广做得太棒了！", cat:"work"});
SENTENCES2.push({en:"Let's table this discussion.", zh:"咱们把这个讨论先搁置。", cat:"work"});
SENTENCES2.push({en:"I need this ASAP.", zh:"我急需这个。", cat:"work"});
SENTENCES2.push({en:"The onboarding starts next week.", zh:"入职培训下周开始。", cat:"work"});
SENTENCES2.push({en:"Let's leverage our strengths.", zh:"咱们发挥优势。", cat:"work"});
SENTENCES2.push({en:"Please find a workaround.", zh:"请想个变通办法。", cat:"work"});
SENTENCES2.push({en:"We're scaling up the team.", zh:"我们正在扩大团队。", cat:"work"});
SENTENCES2.push({en:"The feedback was mostly positive.", zh:"反馈大多是正面的。", cat:"work"});
SENTENCES2.push({en:"Let's close the loop.", zh:"咱们把这事收尾。", cat:"work"});
SENTENCES2.push({en:"I have back-to-back meetings.", zh:"我连着好几个会。", cat:"work"});
SENTENCES2.push({en:"The ROI looks promising.", zh:"投资回报看起来不错。", cat:"work"});
SENTENCES2.push({en:"Let's run the numbers again.", zh:"咱们再核算一下数据。", cat:"work"});
SENTENCES2.push({en:"Please ping me when ready.", zh:"准备好了请叫我。", cat:"work"});
SENTENCES2.push({en:"The stakeholder meeting went well.", zh:"和利益相关方的会议很顺利。", cat:"work"});
SENTENCES2.push({en:"Let's deep dive into the data.", zh:"咱们深入分析一下数据。", cat:"work"});
SENTENCES2.push({en:"I need to delegate this.", zh:"我需要把这事交出去。", cat:"work"});
SENTENCES2.push({en:"The handover is complete.", zh:"交接完成了。", cat:"work"});
SENTENCES2.push({en:"Let's keep the momentum going.", zh:"咱们保持这个势头。", cat:"work"});
SENTENCES2.push({en:"We exceeded expectations.", zh:"我们超出了预期。", cat:"work"});
SENTENCES2.push({en:"Please document the process.", zh:"请把流程记录下来。", cat:"work"});
SENTENCES2.push({en:"The contract is up for renewal.", zh:"合同该续签了。", cat:"work"});
SENTENCES2.push({en:"Let's benchmark against competitors.", zh:"咱们对标一下竞争对手。", cat:"work"});
SENTENCES2.push({en:"I flagged it for review.", zh:"我已标记待审核。", cat:"work"});
SENTENCES2.push({en:"The demo impressed the investors.", zh:"演示给投资人留下了深刻印象。", cat:"work"});
SENTENCES2.push({en:"Let's fast-track this approval.", zh:"咱们加快这个审批。", cat:"work"});
SENTENCES2.push({en:"Teamwork makes it happen.", zh:"团队协作让一切成为可能。", cat:"work"});

// ============ emotion：情感话题（70 条） ============
SENTENCES2.push({en:"I've been feeling down lately.", zh:"我最近情绪有点低落。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to cry.", zh:"想哭就哭，没关系。", cat:"emotion"});
SENTENCES2.push({en:"I'm proud of you.", zh:"我为你感到骄傲。", cat:"emotion"});
SENTENCES2.push({en:"You're not alone in this.", zh:"你不是一个人在面对。", cat:"emotion"});
SENTENCES2.push({en:"I miss you so much.", zh:"我好想你。", cat:"emotion"});
SENTENCES2.push({en:"Take all the time you need.", zh:"需要多久都可以，慢慢来。", cat:"emotion"});
SENTENCES2.push({en:"I'm here for you.", zh:"我会一直陪着你。", cat:"emotion"});
SENTENCES2.push({en:"You did your best.", zh:"你已经尽力了。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to feel sad.", zh:"难过是正常的。", cat:"emotion"});
SENTENCES2.push({en:"I believe in you.", zh:"我相信你。", cat:"emotion"});
SENTENCES2.push({en:"You matter to me.", zh:"你对我很重要。", cat:"emotion"});
SENTENCES2.push({en:"Let's talk it through.", zh:"咱们好好聊聊吧。", cat:"emotion"});
SENTENCES2.push({en:"I'm listening, go ahead.", zh:"我在听，你说。", cat:"emotion"});
SENTENCES2.push({en:"You deserve happiness.", zh:"你值得拥有幸福。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to ask for help.", zh:"寻求帮助没什么不好。", cat:"emotion"});
SENTENCES2.push({en:"I'm worried about you.", zh:"我很担心你。", cat:"emotion"});
SENTENCES2.push({en:"You make me smile.", zh:"你让我开心。", cat:"emotion"});
SENTENCES2.push({en:"I appreciate you.", zh:"我很珍惜你。", cat:"emotion"});
SENTENCES2.push({en:"Take a deep breath.", zh:"深呼吸，放松一下。", cat:"emotion"});
SENTENCES2.push({en:"You've got a kind heart.", zh:"你有一颗善良的心。", cat:"emotion"});
SENTENCES2.push({en:"I'm sorry you're hurting.", zh:"看到你难过，我很心疼。", cat:"emotion"});
SENTENCES2.push({en:"You're stronger than you think.", zh:"你比自己想象的更坚强。", cat:"emotion"});
SENTENCES2.push({en:"I love spending time with you.", zh:"我很喜欢和你在一起的时光。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to say no.", zh:"拒绝也没关系。", cat:"emotion"});
SENTENCES2.push({en:"I'm grateful for you.", zh:"我很感激有你。", cat:"emotion"});
SENTENCES2.push({en:"You light up my day.", zh:"你照亮了我的每一天。", cat:"emotion"});
SENTENCES2.push({en:"I understand how you feel.", zh:"我理解你的感受。", cat:"emotion"});
SENTENCES2.push({en:"You're doing great.", zh:"你做得很棒。", cat:"emotion"});
SENTENCES2.push({en:"I forgive you.", zh:"我原谅你了。", cat:"emotion"});
SENTENCES2.push({en:"Let's make new memories.", zh:"咱们一起创造新的回忆吧。", cat:"emotion"});
SENTENCES2.push({en:"I'm always on your side.", zh:"我永远站在你这边。", cat:"emotion"});
SENTENCES2.push({en:"You inspire me.", zh:"你激励着我。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to rest.", zh:"累了就休息，没关系。", cat:"emotion"});
SENTENCES2.push({en:"I cherish our friendship.", zh:"我珍惜我们的友谊。", cat:"emotion"});
SENTENCES2.push({en:"You're enough, just as you are.", zh:"你本来的样子就足够好。", cat:"emotion"});
SENTENCES2.push({en:"I feel safe with you.", zh:"和你在一起我很有安全感。", cat:"emotion"});
SENTENCES2.push({en:"Let's laugh together.", zh:"咱们一起开怀大笑吧。", cat:"emotion"});
SENTENCES2.push({en:"I'm thinking of you.", zh:"我一直在想你。", cat:"emotion"});
SENTENCES2.push({en:"You have my full support.", zh:"你有我全力支持。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to be vulnerable.", zh:"展现脆弱也没关系。", cat:"emotion"});
SENTENCES2.push({en:"I admire your courage.", zh:"我钦佩你的勇气。", cat:"emotion"});
SENTENCES2.push({en:"You're my favorite person.", zh:"你是我最喜欢的人。", cat:"emotion"});
SENTENCES2.push({en:"I feel lucky to know you.", zh:"认识你是我的幸运。", cat:"emotion"});
SENTENCES2.push({en:"Let's heal together.", zh:"咱们一起疗愈吧。", cat:"emotion"});
SENTENCES2.push({en:"I'm proud of how far you've come.", zh:"你一路走来，我为你骄傲。", cat:"emotion"});
SENTENCES2.push({en:"You bring out the best in me.", zh:"你让我成为更好的自己。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to start over.", zh:"重新开始也没关系。", cat:"emotion"});
SENTENCES2.push({en:"I see the real you.", zh:"我看到了真实的你。", cat:"emotion"});
SENTENCES2.push({en:"You're loved more than you know.", zh:"你被爱着，比你知道的更多。", cat:"emotion"});
SENTENCES2.push({en:"I trust you completely.", zh:"我完全信任你。", cat:"emotion"});
SENTENCES2.push({en:"Let's hold on to hope.", zh:"咱们抱紧希望。", cat:"emotion"});
SENTENCES2.push({en:"I'm here to listen, not judge.", zh:"我只倾听，不评判。", cat:"emotion"});
SENTENCES2.push({en:"You make hard days easier.", zh:"有你在，难熬的日子都变轻松了。", cat:"emotion"});
SENTENCES2.push({en:"I respect your feelings.", zh:"我尊重你的感受。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to change your mind.", zh:"改变主意也没关系。", cat:"emotion"});
SENTENCES2.push({en:"I'm cheering for you.", zh:"我在为你加油。", cat:"emotion"});
SENTENCES2.push({en:"You are my sunshine.", zh:"你是我的阳光。", cat:"emotion"});
SENTENCES2.push({en:"I feel at home with you.", zh:"和你在一起像家一样安心。", cat:"emotion"});
SENTENCES2.push({en:"Let's grow old together.", zh:"咱们一起慢慢变老吧。", cat:"emotion"});
SENTENCES2.push({en:"I'm sorry I hurt you.", zh:"对不起，我伤了你的心。", cat:"emotion"});
SENTENCES2.push({en:"You deserve all good things.", zh:"你值得一切美好。", cat:"emotion"});
SENTENCES2.push({en:"I love your laugh.", zh:"我喜欢你的笑声。", cat:"emotion"});
SENTENCES2.push({en:"It's okay to feel angry.", zh:"生气也是正常的。", cat:"emotion"});
SENTENCES2.push({en:"I'm thankful for this moment.", zh:"我感恩这一刻。", cat:"emotion"});
SENTENCES2.push({en:"You make me a better person.", zh:"你让我成为更好的人。", cat:"emotion"});
SENTENCES2.push({en:"I will never leave you.", zh:"我永远不会离开你。", cat:"emotion"});
SENTENCES2.push({en:"Let's face it together.", zh:"咱们一起面对。", cat:"emotion"});
SENTENCES2.push({en:"I'm honored to know you.", zh:"认识你是我的荣幸。", cat:"emotion"});
SENTENCES2.push({en:"You are deeply loved.", zh:"你被深深地爱着。", cat:"emotion"});
SENTENCES2.push({en:"Home is wherever you are.", zh:"有你的地方就是家。", cat:"emotion"});

// ============ GRAMMAR：语法选择题（100 道） ============
// --- 时态 1-20 ---
GRAMMAR.push({q:"She ___ to school every day.", options:["go","goes","going","went"], a:1, tip:"第三人称单数作主语，一般现在时动词要加 s。"});
GRAMMAR.push({q:"They ___ football yesterday.", options:["play","played","plays","playing"], a:1, tip:"yesterday 是过去时间标志，用一般过去时。"});
GRAMMAR.push({q:"I ___ my homework now.", options:["do","am doing","did","does"], a:1, tip:"now 表示此刻正在进行，用现在进行时。"});
GRAMMAR.push({q:"He ___ in Beijing since 2020.", options:["lives","has lived","is living","lived"], a:1, tip:"since + 过去时间点，从过去持续到现在用现在完成时。"});
GRAMMAR.push({q:"We ___ to the zoo tomorrow.", options:["go","went","will go","going"], a:2, tip:"tomorrow 表将来，用 will + 动词原形。"});
GRAMMAR.push({q:"Look! The baby ___.", options:["cries","is crying","cried","cry"], a:1, tip:"Look! 提示正在发生的动作，用现在进行时。"});
GRAMMAR.push({q:"She ___ already finished her lunch.", options:["has","have","is","was"], a:0, tip:"already 常与现在完成时连用，主语 she 用 has。"});
GRAMMAR.push({q:"When I arrived, they ___ dinner.", options:["have","had","were having","has"], a:2, tip:"过去某一刻正在进行的动作，用过去进行时。"});
GRAMMAR.push({q:"He ___ English for five years.", options:["learns","learned","has learned","is learning"], a:2, tip:"for + 时间段表示持续到现在，用现在完成时。"});
GRAMMAR.push({q:"I ___ TV when you called me.", options:["watched","am watching","was watching","watch"], a:2, tip:"when 从句表过去，正在做的事用过去进行时。"});
GRAMMAR.push({q:"She ___ to London twice.", options:["went","has gone","has been","goes"], a:2, tip:"“去过某地几次”用 have been to。"});
GRAMMAR.push({q:"By next year, he ___ college.", options:["finishes","will finish","will have finished","finished"], a:2, tip:"by + 将来时间点，用将来完成时。"});
GRAMMAR.push({q:"The train ___ at 8:00 every morning.", options:["leaves","is leaving","left","leave"], a:0, tip:"时刻表、班次用一般现在时表示将来。"});
GRAMMAR.push({q:"I ___ my keys. I can't find them.", options:["lost","have lost","lose","loses"], a:1, tip:"过去的动作对现在造成影响，用现在完成时。"});
GRAMMAR.push({q:"She was tired because she ___ all day.", options:["worked","has worked","had worked","works"], a:2, tip:"“过去的过去”用过去完成时。"});
GRAMMAR.push({q:"While he ___, the phone rang.", options:["slept","was sleeping","sleeps","is sleeping"], a:1, tip:"while 后多接进行时态。"});
GRAMMAR.push({q:"They ___ married for ten years.", options:["are","have been","were","will be"], a:1, tip:"持续到现在的状态，用现在完成时。"});
GRAMMAR.push({q:"He ___ his leg last week.", options:["breaks","broke","has broken","is breaking"], a:1, tip:"last week 是明确的过去时间，不用完成时。"});
GRAMMAR.push({q:"I ___ you tomorrow morning.", options:["see","will see","saw","seeing"], a:1, tip:"表将来打算，用 will + 动词原形。"});
GRAMMAR.push({q:"She ___ in this company since she graduated.", options:["works","has worked","worked","is working"], a:1, tip:"since 引导的从句，主句用现在完成时。"});
// --- 冠词 21-30 ---
GRAMMAR.push({q:"___ apple a day keeps the doctor away.", options:["A","An","The","/"], a:1, tip:"apple 以元音音素开头，用 an。"});
GRAMMAR.push({q:"He is ___ honest man.", options:["a","an","the","/"], a:1, tip:"honest 的 h 不发音，首音是元音，用 an。"});
GRAMMAR.push({q:"___ sun rises in the east.", options:["A","An","The","/"], a:2, tip:"太阳是独一无二的事物，用 the。"});
GRAMMAR.push({q:"She plays ___ piano very well.", options:["a","an","the","/"], a:2, tip:"西洋乐器名称前用 the。"});
GRAMMAR.push({q:"I saw ___ interesting movie last night.", options:["a","an","the","/"], a:1, tip:"泛指一部电影，且 interesting 元音开头，用 an。"});
GRAMMAR.push({q:"___ Yangtze River is very long.", options:["A","An","The","/"], a:2, tip:"江河、海洋等名称前用 the。"});
GRAMMAR.push({q:"He is ___ university student.", options:["a","an","the","/"], a:0, tip:"university 发 /ju:/，首音是辅音，用 a。"});
GRAMMAR.push({q:"___ first person to arrive gets a prize.", options:["A","An","The","/"], a:2, tip:"序数词前用 the。"});
GRAMMAR.push({q:"I need ___ hour to finish it.", options:["a","an","the","/"], a:1, tip:"hour 的 h 不发音，用 an。"});
GRAMMAR.push({q:"They had ___ breakfast at seven.", options:["a","an","the","/"], a:3, tip:"三餐名称前一般不加冠词。"});
// --- 介词 31-40 ---
GRAMMAR.push({q:"I was born ___ 2008.", options:["in","on","at","of"], a:0, tip:"年份、月份、季节前用 in。"});
GRAMMAR.push({q:"The meeting is ___ Monday morning.", options:["in","on","at","to"], a:1, tip:"具体某一天（上午/下午）用 on。"});
GRAMMAR.push({q:"She arrived ___ the station at six.", options:["in","on","at","to"], a:2, tip:"arrive at + 小地点，arrive in + 大地点。"});
GRAMMAR.push({q:"He has lived here ___ 2019.", options:["for","since","from","to"], a:1, tip:"since + 过去时间点，for + 时间段。"});
GRAMMAR.push({q:"She is good ___ math.", options:["at","in","on","of"], a:0, tip:"be good at 是固定搭配。"});
GRAMMAR.push({q:"Let's meet ___ the evening.", options:["in","on","at","to"], a:0, tip:"泛指上/下/晚上，用 in the morning/afternoon/evening。"});
GRAMMAR.push({q:"He depends ___ his parents.", options:["in","on","of","to"], a:1, tip:"depend on 是固定搭配。"});
GRAMMAR.push({q:"She arrived ___ Beijing yesterday.", options:["to","in","at","on"], a:1, tip:"arrive 后不加 to，大地点用 in。"});
GRAMMAR.push({q:"I'm interested ___ music.", options:["at","in","on","of"], a:1, tip:"be interested in 是固定搭配。"});
GRAMMAR.push({q:"He knocked ___ the door.", options:["in","on","at","to"], a:1, tip:"knock at/on the door 表示敲门。"});
// --- 主谓一致 41-50 ---
GRAMMAR.push({q:"Neither of the boys ___ here.", options:["are","is","were","be"], a:1, tip:"neither of + 复数名词，谓语仍用单数。"});
GRAMMAR.push({q:"The news ___ shocking.", options:["are","is","were","be"], a:1, tip:"news 形式复数、意义单数，谓语用单数。"});
GRAMMAR.push({q:"Each student ___ a book.", options:["have","has","are having","have got"], a:1, tip:"each 作主语强调个体，谓语用单数。"});
GRAMMAR.push({q:"There ___ some milk in the fridge.", options:["are","is","were","be"], a:1, tip:"milk 不可数，there be 句型谓语用单数。"});
GRAMMAR.push({q:"My family ___ watching TV now.", options:["is","are","was","be"], a:0, tip:"family 作整体看待时，谓语用单数。"});
GRAMMAR.push({q:"A number of students ___ late.", options:["was","is","are","be"], a:2, tip:"a number of + 复数名词，谓语用复数。"});
GRAMMAR.push({q:"The number of cars ___ increasing.", options:["are","is","were","be"], a:1, tip:"the number of 作主语，中心词是 number，用单数。"});
GRAMMAR.push({q:"Physics ___ my favorite subject.", options:["are","is","were","be"], a:1, tip:"学科名称作主语，谓语用单数。"});
GRAMMAR.push({q:"Either you or he ___ right.", options:["are","is","am","be"], a:1, tip:"or 连接主语时谓语与最近的主语一致。"});
GRAMMAR.push({q:"Ten dollars ___ enough for the ticket.", options:["are","is","were","be"], a:1, tip:"钱数、时间、距离作整体，谓语用单数。"});
// --- 比较级最高级 51-60 ---
GRAMMAR.push({q:"This book is ___ than that one.", options:["interesting","more interesting","most interesting","interestinger"], a:1, tip:"多音节形容词比较级用 more + 原级。"});
GRAMMAR.push({q:"He is the ___ boy in class.", options:["tall","taller","tallest","more tall"], a:2, tip:"最高级前要加 the。"});
GRAMMAR.push({q:"My room is ___ than yours.", options:["big","biger","bigger","biggest"], a:2, tip:"big 结尾辅音字母双写再加 er。"});
GRAMMAR.push({q:"Today is ___ than yesterday.", options:["hot","hoter","hotter","hottest"], a:2, tip:"hot 比较级要双写 t。"});
GRAMMAR.push({q:"She is ___ than her sister.", options:["beautifuler","more beautiful","most beautiful","beautiful"], a:1, tip:"beautiful 是多音节词，用 more。"});
GRAMMAR.push({q:"This is the ___ movie I've ever seen.", options:["bad","worse","worst","more bad"], a:2, tip:"bad 的最高级是 worst，不规则变化。"});
GRAMMAR.push({q:"He runs ___ than me.", options:["fast","faster","fastest","more fast"], a:1, tip:"fast 比较级直接加 er。"});
GRAMMAR.push({q:"The ___ you practice, the better.", options:["much","more","most","many"], a:1, tip:"the + 比较级，the + 比较级”表示越……越……"});
GRAMMAR.push({q:"She is two years ___ than me.", options:["old","older","oldest","more old"], a:1, tip:"old 的比较级是 older。"});
GRAMMAR.push({q:"Of the two shirts, this one is ___.", options:["better","best","good","more better"], a:0, tip:"两者之间比较用比较级，不用最高级。"});
// --- 情态动词 61-70 ---
GRAMMAR.push({q:"You ___ finish it today. It's not urgent.", options:["mustn't","don't have to","must","should"], a:1, tip:"don't have to 表示“没必要”，mustn't 表示“禁止”。"});
GRAMMAR.push({q:"She ___ speak three languages.", options:["can","must","should","may"], a:0, tip:"表示能力用 can。"});
GRAMMAR.push({q:"You ___ be quiet in the library.", options:["must","can","may","could"], a:0, tip:"表示必须、规定用 must。"});
GRAMMAR.push({q:"___ I use your phone?", options:["Must","Should","Can","Would"], a:2, tip:"征求许可、请求帮助常用 Can/Could 开头。"});
GRAMMAR.push({q:"He ___ be tired after the long trip.", options:["can","must","may","should"], a:1, tip:"对现在情况的肯定推测用 must。"});
GRAMMAR.push({q:"You ___ eat in class.", options:["mustn't","don't have to","needn't","shouldn't"], a:0, tip:"mustn't 表示禁止，语气最强。"});
GRAMMAR.push({q:"It ___ rain tomorrow. Take an umbrella.", options:["can","must","may","should"], a:2, tip:"表示可能性用 may/might。"});
GRAMMAR.push({q:"Students ___ wear uniforms here.", options:["can","may","must","should"], a:2, tip:"校规、制度要求用 must。"});
GRAMMAR.push({q:"___ you help me with this box?", options:["Must","Should","Can","May"], a:2, tip:"礼貌地请求别人帮忙用 Can/Could。"});
GRAMMAR.push({q:"He ___ have left already.", options:["can","must","may","should"], a:1, tip:"对过去事情的肯定推测用 must have done。"});
// --- 被动语态 71-78 ---
GRAMMAR.push({q:"The cake ___ by my mom.", options:["made","was made","is made","makes"], a:1, tip:"过去发生的被动动作用 was + 过去分词。"});
GRAMMAR.push({q:"English ___ in many countries.", options:["speaks","is spoken","speaking","spoke"], a:1, tip:"一般现在时的被动语态是 is + 过去分词。"});
GRAMMAR.push({q:"The bridge ___ next year.", options:["builds","will build","will be built","is built"], a:2, tip:"将来的被动动作用 will be + 过去分词。"});
GRAMMAR.push({q:"The room ___ every day.", options:["cleans","is cleaned","cleaned","cleaning"], a:1, tip:"every day 表习惯，被动用一般现在时。"});
GRAMMAR.push({q:"The thief ___ by the police yesterday.", options:["caught","was caught","is caught","catches"], a:1, tip:"yesterday 表过去，被动用 was + 过去分词。"});
GRAMMAR.push({q:"This song ___ by a famous singer.", options:["sang","was sung","is sang","sings"], a:1, tip:"sing 的过去分词是 sung，注意不规则变化。"});
GRAMMAR.push({q:"The homework must ___ today.", options:["finish","be finished","finished","finishing"], a:1, tip:"情态动词的被动结构是 be + 过去分词。"});
GRAMMAR.push({q:"My bike ___ stolen last night.", options:["is","was","has","were"], a:1, tip:"last night 是过去时间，被动用 was。"});
// --- 从句 79-86 ---
GRAMMAR.push({q:"I don't know ___ he will come.", options:["that","if","what","which"], a:1, tip:"宾语从句表“是否”，用 if 或 whether。"});
GRAMMAR.push({q:"This is the house ___ I grew up in.", options:["that","where","when","why"], a:0, tip:"句末有介词 in，关系代词指物用 that/which。"});
GRAMMAR.push({q:"The reason ___ he was late is unknown.", options:["why","that","which","when"], a:0, tip:"reason 后的定语从句关系词用 why。"});
GRAMMAR.push({q:"I'll wait ___ he comes back.", options:["until","unless","if","when"], a:0, tip:"wait until 是固定搭配，表示“等到……”。"});
GRAMMAR.push({q:"___ you work hard, you'll succeed.", options:["If","Unless","Until","While"], a:0, tip:"条件状语从句用 if 引导。"});
GRAMMAR.push({q:"She asked me ___ I was tired.", options:["that","if","what","which"], a:1, tip:"间接疑问句（是否）用 if 引导。"});
GRAMMAR.push({q:"I will call you as soon as I ___.", options:["arrive","will arrive","arrived","arriving"], a:0, tip:"时间状语从句中用一般现在时表将来。"});
GRAMMAR.push({q:"That's ___ I disagree with you.", options:["what","why","that","which"], a:1, tip:"表语从句表原因，用 why 引导。"});
// --- some/any、可数不可数 87-94 ---
GRAMMAR.push({q:"Is there ___ milk left?", options:["some","any","many","few"], a:1, tip:"疑问句中用 any，some 多用于肯定句。"});
GRAMMAR.push({q:"I don't have ___ friends here.", options:["some","any","much","little"], a:1, tip:"否定句中用 any。"});
GRAMMAR.push({q:"There are ___ books on the shelf.", options:["much","many","a little","little"], a:1, tip:"可数名词复数用 many。"});
GRAMMAR.push({q:"He doesn't have ___ money.", options:["many","much","a few","few"], a:1, tip:"不可数名词用 much。"});
GRAMMAR.push({q:"She has ___ interesting ideas.", options:["much","a little","little","many"], a:3, tip:"可数名词复数肯定句用 many。"});
GRAMMAR.push({q:"I need ___ water, please.", options:["a few","few","a little","little"], a:2, tip:"不可数名词肯定句用 a little。"});
GRAMMAR.push({q:"___ students passed the exam.", options:["Much","A little","Little","A few"], a:3, tip:"可数名词复数用 a few 表示“一些”。"});
GRAMMAR.push({q:"There isn't ___ time left.", options:["many","much","a few","few"], a:1, tip:"不可数名词否定句用 much。"});
// --- 综合易错 95-100 ---
GRAMMAR.push({q:"Neither he nor I ___ invited.", options:["was","were","am","are"], a:1, tip:"nor 连接主语时谓语与最近的 I 一致，用 were。"});
GRAMMAR.push({q:"He stopped ___ when the teacher came in.", options:["to talk","talking","talk","talked"], a:1, tip:"stop doing 表示停止正在做的事。"});
GRAMMAR.push({q:"I remember ___ the door.", options:["to lock","locking","lock","locked"], a:1, tip:"remember doing 表示记得做过某事。"});
GRAMMAR.push({q:"It's no use ___ over it.", options:["cry","crying","to cry","cried"], a:1, tip:"It's no use doing 是固定句型。"});
GRAMMAR.push({q:"Would you mind ___ the window?", options:["open","opening","to open","opened"], a:1, tip:"mind 后面接动词-ing 形式。"});
GRAMMAR.push({q:"He promised ___ on time.", options:["to come","coming","come","came"], a:0, tip:"promise to do 是固定搭配。"});
