// 短文跟读素材：21 篇中英对照，按难度分级
// lv: 1 初级 / 2 中级 / 3 高级；text/trans 段落一一对应
const PASSAGES = [
/* ---------- 初级 ---------- */
{id:"r01", t:"My Morning", zh:"我的早晨", lv:1, d:"一日之计在于晨",
 text:["I wake up at six thirty every morning. The sun is shining through my window. I get up, wash my face, and brush my teeth. Then I put on my clothes and go to the kitchen.",
 "Mom makes breakfast for me. I like milk and bread. After breakfast, I take my schoolbag and walk to school. A new day begins, and I feel happy."],
 trans:["我每天早上六点半起床。阳光透过窗户照进来。我起床、洗脸、刷牙。然后穿上衣服，去厨房。",
 "妈妈为我做早餐。我喜欢牛奶和面包。早餐后，我背上书包走路去上学。新的一天开始了，我感到很开心。"]},
{id:"r02", t:"A Kind Stranger", zh:"善良的陌生人", lv:1, d:"陌生人的温暖",
 text:["One rainy afternoon, Lily lost her way home. She stood at the bus stop and cried. An old man walked over and asked, \"What is wrong, little girl?\"",
 "\"I cannot find my home,\" Lily said. The old man smiled and took her to the police station. Soon her mother came. Lily said, \"Thank you!\" and the old man waved goodbye."],
 trans:["一个下雨的午后，莉莉迷路了。她站在公交车站哭了起来。一位老人走过来问：\"小姑娘，怎么了？\"",
 "\"我找不到家了，\"莉莉说。老人微笑着把她带到警察局。不久妈妈就来了。莉莉说：\"谢谢您！\"老人挥手告别。"]},
{id:"r03", t:"The Ant and the Grasshopper", zh:"蚂蚁和蚱蜢", lv:1, d:"伊索寓言",
 text:["In summer, the ant works hard every day. She carries food to her home. The grasshopper sings and dances in the sun. \"Why do you work so hard?\" he laughs.",
 "Winter comes. It is cold and snowy. The grasshopper has no food. He is hungry. He goes to the ant and asks for help. The ant shares her food with him. The grasshopper learns: work today, or cry tomorrow."],
 trans:["夏天，蚂蚁每天辛勤工作。她把食物搬回家。蚱蜢在阳光下唱歌跳舞。\"你为什么这么辛苦？\"他笑着问。",
 "冬天来了，又冷又下雪。蚱蜢没有食物，饿极了。他去找蚂蚁求助。蚂蚁把食物分给他。蚱蜢明白了：今日辛勤，明日不愁。"]},
{id:"r04", t:"My Best Friend", zh:"我最好的朋友", lv:1, d:"友谊的模样",
 text:["Tom is my best friend. He is tall and has big eyes. We go to the same school. Every day we play football after class.",
 "Tom is kind. When I am sad, he tells me funny stories. When I have a problem, he helps me. I am lucky to have a friend like Tom."],
 trans:["汤姆是我最好的朋友。他个子高，有一双大眼睛。我们在同一所学校上学。每天放学后我们一起踢足球。",
 "汤姆很善良。我难过时，他给我讲有趣的故事。我有困难时，他帮助我。有汤姆这样的朋友，我很幸运。"]},
{id:"r05", t:"A Rainy Day", zh:"雨天", lv:1, d:"雨也有温柔的一面",
 text:["It is raining outside. I cannot go out to play. I sit by the window and watch the rain. The drops fall on the trees and the ground.",
 "Mom makes hot tea for me. I read my favorite book. The rain sounds like music. A rainy day can be nice, too."],
 trans:["外面下着雨，我不能出去玩。我坐在窗边看雨。雨滴落在树上和地上。",
 "妈妈给我泡了热茶。我读着最喜欢的书。雨声像音乐一样。雨天也可以很美好。"]},
{id:"r06", t:"The Tortoise and the Hare", zh:"龟兔赛跑", lv:1, d:"伊索寓言",
 text:["The hare is fast. The tortoise is slow. One day they have a race. \"You will lose!\" the hare laughs. The tortoise just smiles.",
 "The race begins. The hare runs fast and soon is far away. \"I can take a nap,\" he thinks, and falls asleep under a tree. The tortoise walks and walks, step by step. At last, he passes the sleeping hare and wins the race. Slow and steady wins the race."],
 trans:["兔子跑得快，乌龟爬得慢。一天它们比赛跑步。\"你一定会输！\"兔子大笑。乌龟只是笑笑。",
 "比赛开始了。兔子跑得飞快，很快就遥遥领先。\"我可以睡一觉，\"他想着，便在树下睡着了。乌龟一步一步不停地爬。最后，他超过了熟睡的兔子，赢得了比赛。稳扎稳打者胜。"]},
{id:"r07", t:"My Dream House", zh:"梦想中的房子", lv:1, d:"心中的家",
 text:["I have a dream house in my heart. It is near the sea. In the morning, I can hear the waves. There is a big garden with many flowers.",
 "In my dream house, there is a small library. I can read books all day. My friends often come to visit. We drink tea and talk happily. What a wonderful home!"],
 trans:["我心里有一个梦想中的房子，它在大海边。早晨，我能听见海浪声。房子有一个种满鲜花的大花园。",
 "梦想中的房子里有一个小图书馆，我可以整天读书。朋友们常来做客，我们喝茶聊天，多开心啊。多么美好的家！"]},
/* ---------- 中级 ---------- */
{id:"r08", t:"The Power of Habit", zh:"习惯的力量", lv:2, d:"小习惯，大改变",
 text:["We are what we do every day. A small good habit can change your life. Reading ten pages a day means you can finish many books in a year. Running for twenty minutes a day makes you strong and healthy.",
 "But habits need time. Scientists say it takes about twenty-one days to build a new habit. The first week is the hardest. Many people give up too early.",
 "Here is a good way: start small. Do not try to change everything at once. Do one small thing well, and keep doing it. Day by day, the small habit will grow into a big change."],
 trans:["我们每天做什么，就会成为什么样的人。一个小小的好习惯可以改变人生。每天读十页书，一年就能读完很多本书。每天跑步二十分钟，身体会强壮健康。",
 "但习惯需要时间。科学家说，养成一个新习惯大约需要二十一天。第一周最难，很多人过早放弃了。",
 "有个好方法：从小事做起。不要想一次改变所有事。把一件小事做好，并坚持下去。日复一日，小习惯会带来大改变。"]},
{id:"r09", t:"A Lesson from Failure", zh:"从失败中学到的一课", lv:2, d:"失败是老师",
 text:["When I was twelve, I joined a singing contest at school. I practiced for weeks and felt sure I would win. But on that day, I forgot the words in the middle of the song. I ran off the stage in tears.",
 "I wanted to give up singing. My teacher said to me, \"Failure is not the end. It is a teacher. Ask yourself what went wrong, and try again.\"",
 "The next year, I joined the contest again. This time I practiced harder and stayed calm. I won second place. I learned that failure is not scary. Giving up is."],
 trans:["我十二岁那年参加了学校的歌唱比赛。我练了几个星期，觉得一定能赢。但比赛那天，我唱到一半忘了歌词，哭着跑下了舞台。",
 "我想放弃唱歌。老师对我说：\"失败不是终点，它是一位老师。问问自己哪里出了问题，再试一次。\"",
 "第二年，我又参加了比赛。这次我练得更刻苦，也更冷静。我得了第二名。我明白了：失败不可怕，放弃才可怕。"]},
{id:"r10", t:"The Wind and the Sun", zh:"风与太阳", lv:2, d:"伊索寓言",
 text:["The wind and the sun were arguing about who was stronger. They saw a traveler walking down the road, wearing a warm coat. \"Whoever can make him take off his coat is the stronger one,\" they agreed.",
 "The wind blew hard. It blew and blew. But the harder it blew, the tighter the traveler held his coat. At last the wind gave up.",
 "Then the sun began to shine warmly. The traveler felt warm. He wiped his face and took off his coat with a smile. Gentleness often wins where force fails."],
 trans:["风和太阳争论谁更强大。它们看见一个旅人穿着厚外套走在路上。\"谁能让他脱下外套，谁就更强，\"它们约定。",
 "风猛烈地吹啊吹。但风吹得越猛，旅人把外套裹得越紧。最后风放弃了。",
 "然后太阳温暖地照耀起来。旅人感到暖和，他擦了擦脸，微笑着脱下外套。温柔常常能赢得强力赢不了的东西。"]},
{id:"r11", t:"Why I Love Reading", zh:"我为什么爱阅读", lv:2, d:"书是一扇门",
 text:["Some people ask me why I love reading so much. I tell them: a book is a door. When you open it, you walk into a new world. You can travel to ancient Rome, fly to the moon, or talk with great minds from long ago.",
 "Reading also makes me a better thinker. When I read, I ask questions: Why did he do that? What would I do? A good book does not just tell a story. It teaches you to think.",
 "If you do not like reading yet, start with something fun. A funny story, a comic book, a short novel. Read a little every day. One day you will find that you cannot stop."],
 trans:["有人问我为什么这么爱阅读。我告诉他们：书是一扇门。打开它，你就走进一个新世界。你可以去古罗马旅行，可以飞向月球，可以和古代的智者对话。",
 "阅读还让我更会思考。读书时我会问：他为什么这么做？换作我会怎么做？一本好书不只讲故事，它教你思考。",
 "如果你还不爱阅读，就从有趣的东西开始：一本搞笑的故事书、一本漫画、一本短篇小说。每天读一点，总有一天你会发现自己停不下来。"]},
{id:"r12", t:"A Small Act of Kindness", zh:"小小的善举", lv:2, d:"善良的光",
 text:["Last winter, I saw an old woman selling vegetables by the road. Her hands were red with cold. Few people stopped to buy. I bought some vegetables, though I did not really need them.",
 "She looked at me with surprise and said thanks again and again. Her smile was so warm that I forgot the cold. On my way home, I felt happier than ever.",
 "Kindness does not have to be big. A smile, a helping hand, a few warm words — small acts can light up someone's whole day. And in the end, they light up our own hearts too."],
 trans:["去年冬天，我看见一位老奶奶在路边卖菜，她的手冻得通红。很少有人停下来买。我买了一些菜，虽然我并不真的需要。",
 "她惊讶地看着我，连声道谢。她的笑容那么温暖，让我忘记了寒冷。回家的路上，我感到从未有过的开心。",
 "善良不必惊天动地。一个微笑、一次援手、几句暖心的话——小小的善举能点亮别人的一整天，最终也会照亮我们自己的心。"]},
{id:"r13", t:"Chasing Your Dream", zh:"追逐梦想", lv:2, d:"先迈出第一步",
 text:["Everyone has a dream. Some want to be doctors, some want to be artists, some want to travel the world. But many people keep their dreams in their hearts and never take the first step.",
 "Why? Because they are afraid. Afraid of failing, afraid of what others think, afraid of hard work. But here is the truth: every great success started with a small, scary first step.",
 "You do not need to see the whole road. Just take the first step today. Learn one new thing. Practice for one more hour. Dreams do not come true by waiting. They come true by doing."],
 trans:["人人都有梦想。有人想当医生，有人想当艺术家，有人想环游世界。但很多人把梦想藏在心里，从不迈出第一步。",
 "为什么？因为害怕。怕失败，怕别人怎么看，怕辛苦。但真相是：每个伟大的成功都始于一小步——令人害怕的第一步。",
 "你不需要看清整条路，今天只管迈出第一步。学一样新东西，多练一小时。梦想不会靠等待实现，靠行动实现。"]},
{id:"r14", t:"The Gift of Time", zh:"时间的礼物", lv:2, d:"别浪费它",
 text:["Time is the most precious gift in life, yet we often waste it. We spend hours on our phones, then complain that we have no time to read, to exercise, or to be with family.",
 "The truth is, we all have the same twenty-four hours. The difference is how we use them. Successful people do not have more time. They just use their time better.",
 "Try this: write down how you spend your day. You may be surprised. Then cut one hour of wasted time and give it to something that matters — a book, a walk, a talk with someone you love. Time is a gift. Do not throw it away."],
 trans:["时间是生命中最珍贵的礼物，可我们常常浪费它。我们花几小时刷手机，然后抱怨没时间读书、锻炼、陪家人。",
 "真相是，我们每天都有同样的二十四小时，差别在于怎么用。成功的人并没有更多时间，他们只是更会用时间。",
 "试试这个：记下你一天的时间去向，你可能会大吃一惊。然后砍掉一小时的浪费，把它送给重要的事——一本书、一次散步、一次和所爱之人的交谈。时间是礼物，别随手扔掉。"]},
/* ---------- 高级 ---------- */
{id:"r15", t:"On Perseverance", zh:"论毅力", lv:3, d:"成功者与空想家的区别",
 text:["Talent is common. Ideas are cheap. What truly separates those who succeed from those who only dream is perseverance — the quiet decision to keep going when quitting feels easier.",
 "Think of Thomas Edison. He failed thousands of times before inventing the light bulb. When asked about his failures, he said he had not failed; he had simply found thousands of ways that did not work. That is perseverance: seeing failure as information, not as a verdict.",
 "Perseverance is not about working blindly. It is about adjusting your method while keeping your goal. The river does not break the rock by force, but by flowing around it, day after day.",
 "You do not need to be the smartest person in the room. You only need to be the one who stays the longest. Keep going. The future belongs to those who refuse to stop."],
 trans:["天赋很常见，想法很廉价。真正把成功者与空想家区分开的，是毅力——在放弃更容易时，依然选择前行的安静决定。",
 "想想爱迪生。发明电灯前他失败了上千次。被问及失败时，他说自己并未失败，只是找到上千种行不通的方法。这就是毅力：把失败看作信息，而非判决。",
 "毅力不是盲目蛮干，而是在坚守目标的同时调整方法。河流不是靠蛮力击碎石头，而是日复一日绕过它。",
 "你不必是房间里最聪明的人，只需是待得最久的人。坚持下去，未来属于拒绝停下的人。"]},
{id:"r16", t:"The Art of Slowing Down", zh:"慢的艺术", lv:3, d:"有时最快就是慢",
 text:["We live in a hurry. We eat fast, walk fast, scroll fast. We try to do more in less time, yet we feel we have less time than ever. Somewhere along the way, we forgot how to slow down.",
 "Slowing down is not laziness. It is a skill. When you slow down, you notice things: the taste of your food, the color of the sky, the feeling in your heart. Life becomes richer, not poorer.",
 "Try an experiment this week. Drink your morning tea slowly. Take a walk without your phone. Listen to a friend without thinking about your reply. You will be surprised how much you have been missing.",
 "The clock will keep ticking, but you do not have to race it. Sometimes the fastest way to live well is to slow down."],
 trans:["我们生活在匆忙中。吃饭快、走路快、刷手机快。我们想在更少的时间里做更多的事，却觉得时间越来越不够用。不知何时，我们忘了如何慢下来。",
 "慢下来不是懒惰，而是一种能力。慢下来，你会注意到很多东西：食物的味道、天空的颜色、内心的感受。生活会变得更丰盛，而非更贫乏。",
 "这周做个实验：慢慢喝完早晨的茶，不带手机散一次步，听朋友说话时不想着怎么回复。你会惊讶自己错过了多少。",
 "时钟会一直走，但你不必和它赛跑。有时，过好人生的最快方式，就是慢下来。"]},
{id:"r17", t:"What Success Really Means", zh:"成功真正的含义", lv:3, d:"别追别人定义的成功",
 text:["What is success? A big house? A high salary? A famous name? Society gives us a simple answer: more. More money, more fame, more things. But many people who have \"more\" still feel empty inside.",
 "Perhaps success is not about having more, but about being more. Being more patient, more kind, more honest. Being someone your younger self would be proud of.",
 "True success is quiet. It is the father who reads to his child every night. It is the teacher who stays late to help one student. It is anyone who uses what they have to make life a little better for others.",
 "So do not chase someone else's idea of success. Ask yourself: what kind of person do I want to become? Then walk toward that person, one small step at a time."],
 trans:["什么是成功？大房子？高薪水？名气？社会给了我们一个简单的答案：更多。更多的钱、更多的名、更多的东西。但许多拥有\"更多\"的人，内心依然空虚。",
 "也许成功不在于拥有更多，而在于成为更好的自己。更有耐心、更善良、更诚实，成为让年少的自己骄傲的人。",
 "真正的成功是安静的。是每晚给孩子读书的父亲，是留下来多帮一个学生的老师，是用自己所能让别人的生活变好一点的每一个人。",
 "所以别去追别人定义的成功。问问自己：我想成为什么样的人？然后一步一步，向那个人走去。"]},
{id:"r18", t:"The Fox and the Grapes", zh:"狐狸与葡萄", lv:3, d:"伊索寓言新编",
 text:["On a hot afternoon, a fox walked through a vineyard. High above him hung a bunch of ripe, purple grapes. They looked juicy and sweet in the sunlight.",
 "The fox jumped for them. He missed. He backed up and took a running leap. He missed again. He tried again and again, until he was tired and out of breath.",
 "At last he gave up and walked away, saying to himself, \"Those grapes are probably sour anyway.\" But deep down, he knew the truth: the grapes were sweet. He just could not reach them.",
 "We all do this sometimes. When we cannot have what we want, we tell ourselves we did not want it anyway. It is easier than admitting we failed. But the wiser choice is to ask: how can I grow taller, jump higher, or find another way?"],
 trans:["一个炎热的午后，一只狐狸穿过葡萄园。高高的藤架上挂着一串熟透的紫葡萄，在阳光下看起来多汁又香甜。",
 "狐狸跳起来去够，没够着。他后退几步助跑起跳，又没够着。他一次次尝试，直到精疲力尽、气喘吁吁。",
 "最后他放弃了，边走边安慰自己：\"那些葡萄反正肯定是酸的。\"但他心里清楚：葡萄是甜的，只是自己够不着。",
 "我们有时都这样。得不到想要的东西时，就告诉自己反正也不想要。这比承认失败容易。但更明智的选择是问：我怎样才能长得更高、跳得更远，或找到另一条路？"]},
{id:"r19", t:"Learning a New Language", zh:"学一门新语言", lv:3, d:"像种树一样学习",
 text:["Learning a new language is like planting a tree. At first, nothing seems to happen. You memorize words, and you forget them. You practice sentences, and they sound strange. It feels slow and even hopeless.",
 "But underground, the roots are growing. Every word you learn, every sentence you repeat, is a root going deeper. You cannot see it, but it is there.",
 "Then one day, something changes. You understand a joke in a movie. You have a short talk with a stranger. The tree breaks through the soil. From that moment, growth becomes visible, and learning becomes joyful.",
 "So do not judge your progress by today. Judge it by the roots you are growing. Keep watering the tree. One day, you will sit in its shade."],
 trans:["学一门新语言就像种树。起初似乎什么都没发生。你背单词，又忘掉；你练句子，听起来别扭。感觉又慢又没希望。",
 "但地下，根在生长。你学的每个单词、重复的每个句子，都是一条扎得更深的根。你看不见它，但它在那里。",
 "然后某一天，变化发生了。你听懂了电影里的一个笑话，和陌生人聊了几句。小树破土而出。从那一刻起，成长看得见了，学习也变得快乐。",
 "所以别用今天来判断你的进步，要看你正在扎的根。继续浇水，总有一天，你会坐在树荫下。"]},
{id:"r20", t:"A Letter to My Future Self", zh:"写给未来的自己", lv:3, d:"一封信，跨越时间",
 text:["Dear future me, I am writing this on an ordinary evening. Right now I have more questions than answers. I do not know if my hard work will pay off. I do not know where life will take me.",
 "But I want you to remember this: I am trying. I wake up early to study. I keep going even when I want to quit. If you are reading this and life is good, please know it is because I did not give up today.",
 "If life is still hard, do not blame me. Just keep going a little longer. We have come this far together. Let us see what is around the next corner.",
 "Whatever happens, be kind to yourself. You are doing better than you think. With hope, your past self."],
 trans:["亲爱的未来的我，我在一个平常的夜晚写下这封信。此刻我的问题比答案多。我不知道努力会不会有回报，不知道生活会带我去哪里。",
 "但我想让你记得：我在努力。我早起学习，想放弃时依然坚持。如果你读到这信时生活很好，请知道，那是因为今天的我没有放弃。",
 "如果生活依然艰难，别怪我。再多坚持一会儿。我们已经一起走了这么远，去看看下一个转角有什么。",
 "无论发生什么，对自己温柔一点。你比想象中做得更好。怀着希望，你过去的自己。"]},
{id:"r21", t:"The Strength of Being Vulnerable", zh:"脆弱的力量", lv:3, d:"最勇敢的强大",
 text:["We are taught to be strong. Do not cry. Do not show weakness. Do not let them see you are afraid. So we wear masks and pretend everything is fine, even when our hearts are breaking.",
 "But here is a secret: real strength is not the absence of vulnerability. It is the courage to be vulnerable. The person who says \"I am sad\" is stronger than the one who hides it. The one who asks for help is braver than the one who suffers alone.",
 "When you open your heart, something wonderful happens. Others open theirs too. \"Me too,\" they say. And suddenly you are not alone anymore. Vulnerability builds the deepest connections between people.",
 "So take off the mask sometimes. Let people see the real you — the imperfect, feeling, human you. That is not weakness. That is the bravest kind of strength."],
 trans:["我们被教导要坚强。别哭，别示弱，别让别人看出你害怕。于是我们戴上面具，假装一切都好，即使心已碎裂。",
 "但有个秘密：真正的强大不是没有脆弱，而是有直面脆弱的勇气。说\"我很难过\"的人，比藏起难过的人更强大；开口求助的人，比独自承受的人更勇敢。",
 "当你敞开心扉，奇妙的事发生了：别人也敞开了心扉。\"我也是，\"他们说。突然，你不再孤单。脆弱建立了人与人之间最深的连接。",
 "所以有时摘下面具吧，让别人看见真实的你——不完美的、有感受的、有血有肉的你。那不是软弱，那是最勇敢的强大。"]}
];
